### ISSUE TITLE
Creating new address

### ISSUE THREAD

**Issue by lxjhk** [ethereum/ethereumj#1012]
```Java
import org.ethereum.crypto.ECKey;
import org.ethereum.util.Utils;
import org.spongycastle.util.encoders.Hex;

public class EthereumAccount {
    public static void main(String[] args) {
        ECKey key = new ECKey(Utils.getRandom());

        byte[] pub = key.getPubKey();
        byte[] pri = key.getPrivKeyBytes();
        byte[] addr = key.getAddress();

        String addrBase16 = Hex.toHexString(addr);
        String privBase16 = Hex.toHexString(pri);

        System.out.println("Address     : " + addrBase16);
        System.out.println("Private Key : " + privBase16);
    }


}
```

I am using ethereumj to create key paris for new accounts but the weird thing is that once I reach the line `key.getAddress()`, the whole client seems to start with the following log:

```

14:33:53.492 INFO [general]  Config ( yes ): default properties from resource 'ethereumj.conf'
14:33:53.496 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.res resource 'null'
14:33:53.496 INFO [general]  Config ( no  ): user properties from resource 'user.conf'
14:33:53.505 INFO [general]  Config ( yes ): user properties from file '/config/ethereumj.conf'
14:33:53.505 INFO [general]  Config ( no  ): test properties from resource 'test-ethereumj.conf'
14:33:53.506 INFO [general]  Config ( no  ): test properties from resource 'test-user.conf'
14:33:53.506 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.file file 'null'
14:33:53.506 INFO [general]  Config ( no  ): config passed via constructor
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.ethereum.crypto.ECKey.computeAddress(ECKey.java:438)
	at org.ethereum.crypto.ECKey.computeAddress(ECKey.java:449)
	at org.ethereum.crypto.ECKey.getAddress(ECKey.java:459)
14:33:53.610 ERROR [general]  Can't read config.
	at walletservice.bitcupido.com.EthereumAccount.main(EthereumAccount.java:18)
java.lang.NullPointerException: null
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:219)
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:228)
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:173)
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:173)
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:161)
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:161)
	at org.ethereum.config.SystemProperties.getSpringDefault(SystemProperties.java:104)
	at org.ethereum.config.SystemProperties.getSpringDefault(SystemProperties.java:104)
	at org.ethereum.config.SystemProperties.getDefault(SystemProperties.java:99)
	at org.ethereum.config.SystemProperties.getDefault(SystemProperties.java:99)
	at org.ethereum.crypto.HashUtil.<clinit>(HashUtil.java:55)
	at org.ethereum.crypto.HashUtil.<clinit>(HashUtil.java:55)
	... 4 more
	at org.ethereum.crypto.ECKey.computeAddress(ECKey.java:438)
Caused by: java.lang.NullPointerException
	at org.ethereum.crypto.ECKey.computeAddress(ECKey.java:449)
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:219)
	at org.ethereum.crypto.ECKey.getAddress(ECKey.java:459)
	... 9 more
	at walletservice.bitcupido.com.EthereumAccount.main(EthereumAccount.java:18)

```

`key.getPubKey();` and `key.getPrivKeyBytes();` works perfectly but `key.getAddress();` seems to cause the client to start.

I just want to get the address of the key pair what should I do?

**Comment by mkalinin** [comment]
The code you've shared works. Did you modify `ethereumj.conf` or add a custom config file?

**Comment by zilm13** [comment]
@lxjhk Try latest develop (-SNAPSHOT). It should not fail for you. EthereumJ could read config even in static behaviour, because we don't want to hardcode crypto-providers names and load them from configs. If you think it's not a right approach, we could discuss it.

**Comment by lxjhk** [comment]
Let me try it and I will get back to you. Thanks!

**Comment by zilm13** [comment]
@lxjhk basically I agree that I should expect pure behaviour from static functions and I think about changing this from current code, but it would be good to hear any pro and contra. So we are not closing this issue until final decision.

**Comment by lxjhk** [comment]
Sure, my suggestion is to make the static library does its own things without starting the client. This would all people to use parts of the `Ethereurmj` library conveniently. I am still new into Java. I tried to single step though the code and understand why the whole client is started but could not locate the trigger point in the code.

**Comment by octaplexsys** [comment]
Who can provide latest progress for this issue?
