### ISSUE TITLE
private network  mining Cause a mistake!!! Please help!!! thanks very much

### ISSUE THREAD

**Issue by qq940043871** [ethereum/ethereumj#1022]
Caused by: java.lang.RuntimeException: Invalid Trie state, can't resolve hash 659a32f2610f4b8f76ed9f906d80b8a854573bd57a2dbe2b775ca4997257d7c3
	at org.ethereum.trie.TrieImpl$Node.resolve(TrieImpl.java:111)
	at org.ethereum.trie.TrieImpl$Node.parse(TrieImpl.java:204)
	at org.ethereum.trie.TrieImpl$Node.getType(TrieImpl.java:340)
	at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:537)
	at org.ethereum.trie.TrieImpl.put(TrieImpl.java:531)
	at org.ethereum.trie.SecureTrie.put(SecureTrie.java:47)
	at org.ethereum.trie.SecureTrie.put(SecureTrie.java:26)
	at org.ethereum.datasource.SourceCodec.put(SourceCodec.java:48)
	at org.ethereum.datasource.WriteCache.flush(WriteCache.java:241)
	at org.ethereum.datasource.AbstractChainedSource.flush(AbstractChainedSource.java:66)
	at org.ethereum.datasource.SourceChainBox.flushImpl(SourceChainBox.java:77)
	at org.ethereum.datasource.AbstractChainedSource.flush(AbstractChainedSource.java:64)
	at org.ethereum.db.RepositoryRoot.getRoot(RepositoryRoot.java:120)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:912)
	at org.ethereum.core.BlockchainImpl.createNewBlock(BlockchainImpl.java:505)
	at org.ethereum.core.BlockchainImpl.createNewBlock(BlockchainImpl.java:471)
	at org.ethereum.mine.BlockMiner.getNewBlockForMining(BlockMiner.java:249)
	at org.ethereum.mine.BlockMiner.restartMining(BlockMiner.java:255)
	at org.ethereum.mine.BlockMiner.startMining(BlockMiner.java:141)
	at org.ethereum.mine.BlockMiner.<init>(BlockMiner.java:116)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 67 common frames omitted

genesis-private.json
{
  "nonce": "0x0000000000000088",
  "difficulty": "0x0200",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x",
  "gasLimit": "0x13880000000000",
  "alloc": {
    "0000000000000000000000000000000000000001": { "balance": "1" },
    "0000000000000000000000000000000000000002": { "balance": "1" },
    "0000000000000000000000000000000000000003": { "balance": "1" },
    "0000000000000000000000000000000000000004": { "balance": "1" },
    "102e61f5d8f9bc71d0ad4a084df4e65e05ce0e1c": { "balance": "1606938044258990275541962092341162602522202993782792835301376" },
    "cd2a3d9f938e13cd947ec05abc7fe734df8dd826": { "balance": "10000000000000000" }
  },
  "config": {
    "homesteadBlock": 20,
    "daoForkBlock": 20,
    "daoForkSupport": false,
    "eip150Block": 20,
    "eip158Block": 20,
    "eip155Block": 20
  }
}

**Comment by qq940043871** [comment]
when my genesis-private.json change 
`{
  "nonce": "0x0000000000000088",
  "difficulty": "0x0200",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x",
  "gasLimit": "0x13880000000000",
  "alloc": {
  },
  "config": {
    "homesteadBlock": 20,
    "daoForkBlock": 20,
    "daoForkSupport": false,
    "eip150Block": 20,
    "eip158Block": 20,
    "eip155Block": 20
  }
}
`
the problem is missing!
but when miner_start block mined ,my coinbase address balance is always 0

**Comment by mkalinin** [comment]
could you please close this one too?

**Comment by qq940043871** [comment]
ok！thank you again
