### ISSUE TITLE
Standalone execution

### ISSUE THREAD

**Issue by pschweitz** [ethereum/ethereumj#1090]
Hi,
I am wondering to build an application in Java on top of ethereumj.

I was seeing that it is not possible to execute ethereumj in a standalone node at all, for development purpose.

Either if I start mining without sync, the Ethreum crashes with a NullPointerException (at org.ethereum.mine.BlockMiner.getNewBlockForMining(BlockMiner.java:246)).
Or if I enable syncing and mining, the sync manager loops on waiting for a new block before triggering the event "onSyncDone" to start the mining (BlockMiner.java: line 106). 

It is a deadlock for such use case, except if I trigger manually the mining which would also cause further issues and/or racing conditions at the time when I add other nodes in a private network... at syncing time.

For resolution I would suggest to trigger the "onSyncDone" event when the last block imported by the sync manager is the last best known, rather than waiting for a new block everytime.

Please find following the config I used, and the ethereumj.log content:

## config: 

peer.discovery.enabled = false
peer.listen.port = 0
peer.networkId = 444
sync.enabled = true // or false
genesis = xxx.json
database.dir = xxx
ethash.dir = xxx
mine.start = true
mine.cpuMineThreads = 2
mine.minGasPrice = 150
mine.fullDataSet = true
database.reset = false 
cache.flush.blocks = 0

## ethreumj.log:

10:32:25.740 [main] INFO  general - Starting EthereumJ...
10:32:26.994 [main] INFO  general - Config ( yes ): default properties from resource 'ethereumj.conf'
10:32:26.994 [main] INFO  general - Config ( no  ): user properties from -Dethereumj.conf.res resource 'null'
10:32:26.995 [main] INFO  general - Config ( no  ): user properties from resource 'user.conf'
10:32:26.996 [main] INFO  general - Config ( no  ): user properties from file '/xxx/config/ethereumj.conf'
10:32:26.996 [main] INFO  general - Config ( no  ): test properties from resource 'test-ethereumj.conf'
10:32:26.996 [main] INFO  general - Config ( no  ): test properties from resource 'test-user.conf'
10:32:26.997 [main] INFO  general - Config ( no  ): user properties from -Dethereumj.conf.file file 'null'
10:32:26.997 [main] INFO  general - Config ( no  ): config passed via constructor
10:32:27.040 [main] INFO  general - Running xxx.json,  core version: 1.8.0-SNAPSHOT
10:32:27.042 [main] INFO  general - git.hash: []
10:32:27.043 [main] INFO  general - build.time: [GMT]-[31/May/2018]-[08:07]
10:32:27.044 [main] INFO  general - Database directory location: 'xxx', version: 6
10:32:27.045 [main] INFO  general - capability eth version: [62, 63]
10:32:27.045 [main] INFO  general - capability shh version: [3]
10:32:27.045 [main] INFO  general - capability bzz version: [0]
10:32:27.805 [main] DEBUG db - ~> RocksDbDataSource.init(): blockchain
10:32:27.811 [main] DEBUG db - Opening database
10:32:27.812 [main] DEBUG db - Initializing new or existing database: 'blockchain'
10:32:27.854 [main] DEBUG db - <~ RocksDbDataSource.init(): blockchain
10:32:27.854 [main] INFO  general - rocksdb key-value data source created: blockchain
10:32:28.176 [main] DEBUG db - ~> RocksDbDataSource.init(): peers
10:32:28.176 [main] DEBUG db - Opening database
10:32:28.176 [main] DEBUG db - Initializing new or existing database: 'peers'
10:32:28.220 [main] DEBUG db - <~ RocksDbDataSource.init(): peers
10:32:28.220 [main] INFO  general - rocksdb key-value data source created: peers
10:32:28.233 [main] INFO  general - External IP wasn't set, using checkip.amazonaws.com to identify it...
10:32:28.636 [main] INFO  general - External address identified: 92.184.105.4
10:32:28.661 [main] INFO  mine - Sync disabled, start mining now...
10:32:28.661 [main] INFO  mine - Miner started
10:32:28.664 [main] INFO  db - Flushing DBs...
10:32:28.665 [main] DEBUG db - Flipping async storages
10:32:28.665 [main] DEBUG db - Submitting flush task
10:32:28.666 [DbFlushManagerThread-0] INFO  db - Flush started
10:32:28.668 [DbFlushManagerThread-0] DEBUG db - AsyncWriteCache (state): flush submitted
10:32:28.670 [AsyncWriteCacheThread-0] DEBUG db - AsyncWriteCache (state): flush started
10:32:28.672 [AsyncWriteCacheThread-0] DEBUG db - AsyncWriteCache (state): flush completed in 2 ms
10:32:28.672 [DbFlushManagerThread-0] DEBUG db - AsyncWriteCache (journal): flush submitted
10:32:28.673 [AsyncWriteCacheThread-1] DEBUG db - AsyncWriteCache (journal): flush started
10:32:28.673 [AsyncWriteCacheThread-1] DEBUG db - AsyncWriteCache (journal): flush completed in 0 ms
10:32:28.675 [DbFlushManagerThread-0] DEBUG db - AsyncWriteCache (block): flush submitted
10:32:28.675 [AsyncWriteCacheThread-0] DEBUG db - AsyncWriteCache (block): flush started
10:32:28.676 [AsyncWriteCacheThread-0] DEBUG db - AsyncWriteCache (block): flush completed in 0 ms
10:32:28.676 [DbFlushManagerThread-0] DEBUG db - AsyncWriteCache (index): flush submitted
10:32:28.679 [AsyncWriteCacheThread-1] DEBUG db - AsyncWriteCache (index): flush started
10:32:28.680 [AsyncWriteCacheThread-1] DEBUG db - AsyncWriteCache (index): flush completed in 1 ms
10:32:28.680 [DbFlushManagerThread-0] DEBUG db - AsyncWriteCache (transactions): flush submitted
10:32:28.680 [AsyncWriteCacheThread-0] DEBUG db - AsyncWriteCache (transactions): flush started
10:32:28.680 [AsyncWriteCacheThread-0] DEBUG db - AsyncWriteCache (transactions): flush completed in 0 ms
10:32:28.680 [DbFlushManagerThread-0] DEBUG db - AsyncWriteCache (block): flush submitted
10:32:28.680 [AsyncWriteCacheThread-1] DEBUG db - AsyncWriteCache (block): flush started
10:32:28.680 [AsyncWriteCacheThread-1] DEBUG db - AsyncWriteCache (block): flush completed in 0 ms
10:32:28.681 [DbFlushManagerThread-0] DEBUG db - AsyncWriteCache (index): flush submitted
10:32:28.681 [AsyncWriteCacheThread-0] DEBUG db - AsyncWriteCache (index): flush started
10:32:28.681 [AsyncWriteCacheThread-0] DEBUG db - AsyncWriteCache (index): flush completed in 0 ms
10:32:28.681 [DbFlushManagerThread-0] DEBUG db - Flushing to DB
10:32:28.681 [DbFlushManagerThread-0] INFO  db - Flush completed in 14 ms
10:32:28.681 [main] INFO  db - Flush done.
10:32:28.681 [main] INFO  db - Closing DB: peers
10:32:28.682 [main] DEBUG db - Close db: peers
10:32:28.682 [main] INFO  db - Closing DB: blockchain
10:32:28.682 [main] DEBUG db - Close db: blockchain
10:32:28.687 [main] ERROR general - Uncaught exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMiner' defined in URL [jar:file:xxx/lib/ethereumj-core-1.8.0-SNAPSHOT.jar!/org/ethereum/mine/BlockMiner.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.mine.BlockMiner]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:63)
	at com.xxx.Main.main(Main.java:220)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.mine.BlockMiner]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 14 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.ethereum.mine.BlockMiner.getNewBlockForMining(BlockMiner.java:246)
	at org.ethereum.mine.BlockMiner.restartMining(BlockMiner.java:255)
	at org.ethereum.mine.BlockMiner.startMining(BlockMiner.java:141)
	at org.ethereum.mine.BlockMiner.<init>(BlockMiner.java:116)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 16 common frames omitted
 ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  

 ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  

10:33:11.060 [main] INFO  general - Starting EthereumJ...
10:33:12.358 [main] INFO  general - Config ( yes ): default properties from resource 'ethereumj.conf'
10:33:12.358 [main] INFO  general - Config ( no  ): user properties from -Dethereumj.conf.res resource 'null'
10:33:12.360 [main] INFO  general - Config ( no  ): user properties from resource 'user.conf'
10:33:12.361 [main] INFO  general - Config ( no  ): user properties from file '/xxx/config/ethereumj.conf'
10:33:12.361 [main] INFO  general - Config ( no  ): test properties from resource 'test-ethereumj.conf'
10:33:12.362 [main] INFO  general - Config ( no  ): test properties from resource 'test-user.conf'
10:33:12.362 [main] INFO  general - Config ( no  ): user properties from -Dethereumj.conf.file file 'null'
10:33:12.362 [main] INFO  general - Config ( no  ): config passed via constructor
10:33:12.412 [main] INFO  general - Running xxx.json,  core version: 1.8.0-SNAPSHOT
10:33:12.414 [main] INFO  general - git.hash: []
10:33:12.415 [main] INFO  general - build.time: [GMT]-[31/May/2018]-[08:07]
10:33:12.416 [main] INFO  general - Database directory location: 'xxx', version: 6
10:33:12.417 [main] INFO  general - capability eth version: [62, 63]
10:33:12.417 [main] INFO  general - capability shh version: [3]
10:33:12.418 [main] INFO  general - capability bzz version: [0]
10:33:13.285 [main] DEBUG db - ~> RocksDbDataSource.init(): blockchain
10:33:13.293 [main] DEBUG db - Opening database
10:33:13.293 [main] DEBUG db - Initializing new or existing database: 'blockchain'
10:33:13.337 [main] DEBUG db - <~ RocksDbDataSource.init(): blockchain
10:33:13.337 [main] INFO  general - rocksdb key-value data source created: blockchain
10:33:13.678 [main] DEBUG db - ~> RocksDbDataSource.init(): peers
10:33:13.678 [main] DEBUG db - Opening database
10:33:13.679 [main] DEBUG db - Initializing new or existing database: 'peers'
10:33:13.714 [main] DEBUG db - <~ RocksDbDataSource.init(): peers
10:33:13.715 [main] INFO  general - rocksdb key-value data source created: peers
10:33:13.726 [main] INFO  general - External IP wasn't set, using checkip.amazonaws.com to identify it...
10:33:14.157 [main] INFO  general - External address identified: 92.184.105.4
10:33:14.192 [main] INFO  general - EthereumJ node started: enode://89aa8c91c5360a0a5371de1a2003f2e8edf9190dd3eb6bedfec5eca01e3db19be5d6c2cef5922bc5621b5335fc27b807def47dbab9117b4b5ef6bdb22c269d85@92.184.105.4:0
10:33:14.212 [main] INFO  general - DB is empty - adding Genesis
10:33:14.231 [main] INFO  general - Genesis block loaded
10:33:14.264 [main] INFO  general - Bind address wasn't set, Punching to identify it...
10:33:14.344 [main] INFO  general - UDP local bound to: 192.168.1.9
10:33:14.358 [main] INFO  sync - Sync Manager: ON
10:33:14.359 [main] INFO  sync - Initializing SyncManager.
10:33:14.361 [main] INFO  sync - Initializing SyncManager regular sync.
10:33:14.363 [main] INFO  sync - RegularSync: Initializing BlockDownloader.
10:33:14.366 [SyncThreadHeaders] DEBUG sync - ##########  RegularSync: New header requests (1):
    HeadersRequest{start=1, count=192, reverse=false, step=0}
10:33:14.367 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:14.522 [main] INFO  general - Ethereum listener added
10:33:14.841 [startPlatform] DEBUG pending - PendingTransactionUpdate: (Tot:   1)  NEW_PENDING : 13d9fbd3        0 #0 (e1116d <~ 000000) Txs:0, Unc: 0 []
10:33:14.841 [startPlatform] DEBUG pending - Wire transaction list added: total: 1, new: 1, valid (added to pending): [TransactionData [hash=02e889c35ee6745aab43f581b165be2b60b974cd286c9808965d0a8a7df4d3a4  nonce=00, gasPrice=2710, gas=016f50, receiveAddress=13d9fbd31b941347f7a00d993a2b47c1ecb05711, sendAddress=13d9fbd31b941347f7a00d993a2b47c1ecb05711, value=, data=5b22[...], signatureV=28, signatureR=8abb7c86b914f7fcc34aef66d823a45f5d024b98a601fb96c146fd3eda8d581e, signatureS=1aec45382dae98d276db301c84360439ee79eb2faa4436d67fe8dd138ccc2ab0]] (current #of known txs: 1)
10:33:14.867 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:15.368 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:15.869 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:16.369 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:16.870 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:17.373 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:17.874 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:18.374 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:18.875 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:19.376 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:19.876 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:20.377 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:20.878 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:21.378 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:21.879 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:22.379 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:22.880 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:23.383 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:23.884 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:24.358 [pool-5-thread-1] INFO  sync - Sync state: Regular (0 of 0), last block #0, best known #0
10:33:24.384 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:24.885 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:25.387 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:25.888 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:26.389 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:26.889 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:27.389 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:27.890 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:28.391 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:28.891 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:29.392 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:29.893 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:30.394 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:30.894 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:31.395 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:31.896 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:32.396 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:32.897 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:33.398 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:33.898 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found
10:33:34.358 [pool-5-thread-1] INFO  sync - Sync state: Regular (0 of 0), last block #0, best known #0
10:33:34.399 [SyncThreadHeaders] DEBUG sync - RegularSync headerRetrieveLoop: No IDLE peers found

**Comment by pschweitz** [comment]
Hi again,

I made a trial with an extended sync manager which releases the blockminer if there is no peer connection after some time (the case with a sync manager started -> see my previous message).

I get the same result. Apparently it is the following method that returns a null object:
((PendingStateImpl) pendingState).getBestBlock();

I tried to comment the debug trace line, but I still get a NullPointerException afterwards, please see the stack trace:

17:01:15.788 [xxx] ERROR c.i.r.c.standard.StandaloneConfig - Uncaught exception
java.lang.NullPointerException: null
	at org.ethereum.core.PendingStateImpl.executeTx(PendingStateImpl.java:413)
	at org.ethereum.core.PendingStateImpl.addPendingTransactionImpl(PendingStateImpl.java:226)
	at org.ethereum.core.PendingStateImpl.addPendingTransactions(PendingStateImpl.java:166)
	at org.ethereum.core.PendingStateImpl.addPendingTransaction(PendingStateImpl.java:156)
	at org.ethereum.facade.EthereumImpl.submitTransaction(EthereumImpl.java:216)

It seems it is not possible to submit a transaction at all !? Or I am wrong somewhere ?

Thank you for you support !

**Comment by zilm13** [comment]
@pschweitz we will review this issue a bit later.
Looks like `BlockMiner` auto start is using something that is not initialized early. It is not reproduced locally for me, but order of Spring `@Autowire` is not guaranteed, so I guess it's a reason of this issue.

Also to execute mining manually before sync is over (detecting sync finish automatically in private networks could be complicated) we have this approach:
https://github.com/ether-camp/ethereum-harmony/blob/develop/src/main/java/com/ethercamp/harmony/jsonrpc/EthJsonRpcImpl.java#L1404-L1411

For the second case, could you provide full log from the beginning? It looks like you are submitting tx before application finished startup.
