### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#1111]
```
02:34:06.742 DEBUG [sync]  BlockQueue size: 448, headers queue size: 1152, blocks in mem: 448 (~11mb)
02:34:06.743 ERROR [sync]  Error processing block #3431853 (eb20fe <~ 3c216d) Txs:13, Unc: 0:
java.lang.NullPointerException: Data must not be null
        at org.ethereum.db.ByteArrayWrapper.<init>(ByteArrayWrapper.java:38)
        at org.ethereum.core.BlockchainImpl.isValid(BlockchainImpl.java:744)
        at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:561)
        at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:530)
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:437)
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:289)
        at java.lang.Thread.run(Thread.java:745)
02:34:06.743 ERROR [sync]  Block dump: f90867f90207a03c216d541d4535cf05e684983483aeb5a200a2f47f6f9a0018c8afd6d2244336a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479400d8c82eb65124ea345
2cac59b64acc230aa3482a01477a7dc25b9eb6215acc8b42b2804749cf9672927fb3aa913394c9decc21fd2a0d350f3910ebf8d7f4ba5dd02bb51c666932532b125683634534a0bc27cf37cc6a09f3dde55c836b70619e6c2c10c6572bd3ffdd07f17532cfb7
83c69c74ea3d1abb90100000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000180000000000000000000000000000000
000000000000000000000000000000000000000000000000180000000000000100000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000200000000000000000000000000000000000000000000000000000000000000000000000000000000200000020000000000000000000000004000000084160167af83345dad8389321b8304c72f845b21e132892f4254432e434f4d2fa09ccbc03e33b95
27fe4ee347996f946aa91ddb17b060593141350f65ff530939988282a072402bd659cf90659ea80843b9aca0083015f90948921ebb5f79e9e3920abe571004d0b1d5119c154865af3107a400080038080f86b0d843b9aca008252089481b7e08f65bdf564860
6c89998a9cc8164397647880de0b6b3a76400008029a0ba1650dc939a2cfb321aa7f0e0049d30a7cbba6b899e23f46bb83bbd1ac07414a018ef449ade333a190b2988bc209c845e62abc27ae9543a7523f7a7af5a138190f8aa8220d2843b9aca00826f6a943
d97b0373e6fd034f66e018a0c6ff301055ffbc980b8447183616c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000001ca0b0d4254739827b50381
26eff2c792349709e99400696ddfd954e1ede748b57eea0675821ee77e532c2bd4ba48f654159eed750c54f4c6292b971fd28c1e47a02b6f86e83996662843b9aca0082520894e86be42212952bd028dc2cb76150648795e668e0880de0b6b3a7640000801ca
0f628ea85bbb51d167a055200e1af96fc777f1e1af8948dcffaae75558f8f73a4a041a923f554b7b4aa0802d82711e1698a62fc301cc7339dfdd81e8d362531593df8ab8201ff843b9aca008301388094a63b277ac1df94d9ddf9bc3504af2e47dc17555680b
844a9059cbb000000000000000000000000815dbfd2aff5ba155d9ec61ddb251cedc9b355550000000000000000000000000000000000000000000000000de0b6b3a76400001ca0a2399ceb24506711ffe1c439ebad5a32ddaa3db2c18bd584704a1d02bd64a
7b7a02594fecbf006a48123b6af3269715f2fb89227b97b9fb2ee02413d9956097fe2f86e83996663843b9aca0082520894e86be42212952bd028dc2cb76150648795e668e0880de0b6b3a7640000801ca097439fde100765915176112d5cbb5805ba9e21a1d513f7bf31d6f8ff0fca5f23a0044951d26382a4329e595404988f31d27b8a3945420dd72a48e51219fd2af831f8aa8220d3843b9aca00826f6a943d97b0373e6fd034f66e018a0c6ff301055ffbc980b8447183616c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000001ca067eac0c5fd64029f50eb92d1b34178cb8a8545d6abe621a4bb26e88d432b0475a050058076505949750d97d53a5b9ba49ff09b2f3fd7859626d269da906bffd1e0f86e83996664843b9aca0082520894e86be42212952bd028dc2cb76150648795e668e0880de0b6b3a7640000801ca00ac54d12b0c07fe4b77623a685dc68efb05e9c7161e421d5156cf2276e047f46a00154fd763cec35bd1db7e8e1b9e6873f023ef06ba40fe1eee73687e9e4f53c7ff8aa8220d4843b9aca00826f6a943d97b0373e6fd034f66e018a0c6ff301055ffbc980b8447183616c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000001ca0dec994e9e556f2b3eb6cfe99d7abf9892939680ce22aca795a001edace13bc96a027f0b70d1cc66291dfd9072209e08a5fc813271b51cbb7d4b44f6bbc454bdb6cf86e83996665843b9aca0082520894e86be42212952bd028dc2cb76150648795e668e0880de0b6b3a7640000801ba0fe2a0f8737328b907a1f268e576d1f0776518f1126524bfd0df8b64b198e32e7a01e90059c89a7fbb05e4b83d68f9d61470b942f449377f8b9d424a17420e44cdef86e83996666843b9aca0082520894e86be42212952bd028dc2cb76150648795e668e0880de0b6b3a7640000801ba021dab280a5500c70b17c5a8efd3888f75e857c8ccfa7d37800f73e88de70ad78a02799bb23c1166ab3ce3b7f83c9b02b46608d27271f31e022dc1544c0d1e0f91cf86e83996667843b9aca0082520894e86be42212952bd028dc2cb76150648795e668e0880de0b6b3a7640000801ca02a29b0efd7b2c4c322d326e0b2ce1a63686ad05d8a907b019b7880faa1f8a655a038985275710d2b74b3764aa63e582ea91ada63e3bfb06ee3f77c31268609ff42f86e83996668843b9aca0082520894e86be42212952bd028dc2cb76150648795e668e0880de0b6b3a7640000801ca05326a05825d2c386845aec256453b2bea6bd51706cf4426632d9788bce2dfdc6a05423aa95ed9abe2ef070e99f3c8a8a2d4983004370cca2777d74aaaa2a7bd286c0
02:34:06.743 DEBUG [sync]  BlockQueue size: 447, headers queue size: 1152, blocks in mem: 447 (~11mb)
02:34:06.744 ERROR [sync]  No parent on the chain for block.number: 3431854 block.hash: c8df56
```
Not reproduced on restart

**Comment by zilm13** [comment]
Partially solved with https://github.com/ethereum/ethereumj/commit/2009deaa915376772e46b9638b7f33cbda0820b4
but it could be improved further with INVALID fork reject.
So not closing it.

**Comment by zilm13** [comment]
Here's the idea how to fix it:
If we get `INVALID` import result in `SyncManager`, we should reject part of chain starting from invalid block (and including it) from `SyncQueue`. Both for chain and `SyncQueue` maximum number of blocks to step backwards = 192, so if we already downloaded more than 192 blocks after invalid one, we are unable to jump to the correct fork even if we get good peer.
