### ISSUE TITLE
Ethereum not starting (config?)

### ISSUE THREAD

**Issue by redskate** [ethereum/ethereumj#1113]
Hi

the statement

ethereum = EthereumFactory.createEthereum();

generates an exception (why and how can I please quickly correct it?)
I suppose something with init. I am normally not using the Spring framework, so my question might be interpreted as naive. Please help!

Thank you in advance
Regards

THe exception:
`
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.ethereum.config.SystemProperties org.ethereum.config.DefaultConfig.config; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'systemProperties' defined in class org.ethereum.config.CommonConfig: Initialization of bean failed; nested exception is java.lang.NoSuchFieldError: ACCEPT_CASE_INSENSITIVE_PROPERTIES
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:63)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:44)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:40)
	at com.semweb.blockchain.eth.EthereumInteraction.<init>(EthereumInteraction.java:33)
	at com.semweb.skosshuttle.engine.S2MEngine.test_bc_ethereum_account(S2MEngine.java:25296)
	at com.semweb.skosshuttle.engine.S2MEngineActions.on_bc_testsettings(S2MEngineActions.java:1549)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.semweb.skosshuttle.engine.S2MEngineActions.doGet(S2MEngineActions.java:826)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1096)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.ethereum.config.SystemProperties org.ethereum.config.DefaultConfig.config; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'systemProperties' defined in class org.ethereum.config.CommonConfig: Initialization of bean failed; nested exception is java.lang.NoSuchFieldError: ACCEPT_CASE_INSENSITIVE_PROPERTIES
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 45 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'systemProperties' defined in class org.ethereum.config.CommonConfig: Initialization of bean failed; nested exception is java.lang.NoSuchFieldError: ACCEPT_CASE_INSENSITIVE_PROPERTIES
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 47 more
Caused by: java.lang.NoSuchFieldError: ACCEPT_CASE_INSENSITIVE_PROPERTIES
	at org.ethereum.core.genesis.GenesisLoader.loadGenesisJson(GenesisLoader.java:119)
	at org.ethereum.core.genesis.GenesisLoader.loadGenesisJson(GenesisLoader.java:70)
	at org.ethereum.config.SystemProperties.getGenesisJson(SystemProperties.java:926)
	at org.ethereum.config.SystemProperties.getBlockchainConfig(SystemProperties.java:323)
	at org.ethereum.config.Initializer.initConfig(Initializer.java:66)
	at org.ethereum.config.Initializer.postProcessBeforeInitialization(Initializer.java:82)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	... 56 more
`

**Comment by redskate** [comment]
The problem seems to be, that 

org.ethereum.core.genesis.GenesisLoader.loadGenesisJson(GenesisLoader.java:119)

references

ObjectMapper mapper = new ObjectMapper()
                    .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                    .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES);

But in the bound libary **com.fasterxml.jackson.databind.MapperFeature** inside the built jar package "**ethereumj-core-1.9.0-SNAPSHOT-all.jar**" **there is NO MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES**

Build - error?

**Comment by redskate** [comment]
This was a library bind error. In fact java took com.fasterxml.jackson.databind from another library (older) and this caused the problem. I renamed that library with a name starting after "e" like ethereumj-core-1.9.0-SNAPSHOT-all.jar
