### ISSUE TITLE
ethereumj + parity no peer

### ISSUE THREAD

**Issue by vachrushev** [ethereum/ethereumj#1140]
Hello. My ethereumj app not sync block chain.
**App:**  ([Link in pastebin](https://pastebin.com/tPmkXM41) ) 
```
public class Main extends EthereumListenerAdapter {
    public static void main(String[] args) {
        Ethereum ethereum = EthereumFactory.createEthereum();
        ethereum.addListener(new Main());
    }
}
```
**ethereumj.conf :** ([Link in pastebin](https://pastebin.com/uRBrqDiU))
```
peer = {
    discovery.enabled = false
    listen.port = 0
    active = [
        {url = "enode://f43e4c5d672d3054786aa5eb4e7efe9bcb41d9b5faa6858dd0176d516c37373f56e073b71e0b80ec487b29d087e9e747eb5d76c80b9cfb7c626c047f8f0fa1e6@192.168.0.114:30303"}
      ]
}
peer.networkId = 8690
peer.p2p.eip8 = false
blockchain.config.name = "testnet"
database {
    # place to save physical storage files
    dir = database-parity
}
peer.discovery.enabled = true
database.reset = false
sync.enabled = true
sync.fast.enabled = true
keyvalue.datasource = rocksdb
```
**Parity start:**
parity --config dev 

**Parity logs:** ([Link in pastebin](https://pastebin.com/abjmCSTb))
```
018-08-02 12:13:49  Starting Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
2018-08-02 12:13:49  Keys path /home/user/.local/share/io.parity.ethereum/keys/DevelopmentChain
2018-08-02 12:13:49  DB path /home/user/.local/share/io.parity.ethereum/chains/DevelopmentChain/db/1484bce8c021f2ca
2018-08-02 12:13:49  State DB configuration: fast
2018-08-02 12:13:49  Operating mode: active
2018-08-02 12:13:49  Configured for DevelopmentChain using InstantSeal engine
2018-08-02 12:13:54  Public node URL: enode://f43e4c5d672d3054786aa5eb4e7efe9bcb41d9b5faa6858dd0176d516c37373f56e073b71e0b80ec487b29d087e9e747eb5d76c80b9cfb7c626c047f8f0fa1e6@192.168.0.114:30303
2018-08-02 12:14:24     0/25 peers   9 KiB chain 32 KiB db 0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2018-08-02 12:14:54     0/25 peers   9 KiB chain 32 KiB db 0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
....
```

**App logs:** ([Link in pastebin](https://pastebin.com/W75t7nvm))

```
14:17:03.506 INFO [general]  Config ( yes ): default properties from resource 'ethereumj.conf'
14:17:03.506 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.res resource 'null'
14:17:03.507 INFO [general]  Config ( no  ): user properties from resource 'user.conf'
14:17:03.507 INFO [general]  Config ( no  ): user properties from file '/home/user/work/ethereum/config/ethereumj.conf'
14:17:03.507 INFO [general]  Config ( no  ): test properties from resource 'test-ethereumj.conf'
14:17:03.507 INFO [general]  Config ( no  ): test properties from resource 'test-user.conf'
14:17:03.507 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.file file 'null'
14:17:03.507 INFO [general]  Config ( no  ): config passed via constructor
14:17:03.525 INFO [general]  Running frontier.json,  core version: 1.8.1-RELEASE
14:17:03.526 INFO [general]  git.hash: [a47945b]
14:17:03.526 INFO [general]  build.time: [GMT]-[26/Jun/2018]-[18:27]
14:17:03.527 INFO [general]  Created database version file
14:17:03.527 INFO [general]  capability eth version: [62, 63]
14:17:03.527 INFO [general]  capability shh version: [3]
14:17:03.527 INFO [general]  capability bzz version: [0]
14:17:04.110 INFO [general]  New nodeID generated: c43d9c4970fa1f336723981e1113fa893f2a84a244d9b7da83545e99b0963f2d39d997bb0ff4f34c6b3c83e7a5caab16bc931ad7b821475ae9393bac0ae86344
14:17:04.110 INFO [general]  Generated nodeID and its private key stored in database-parity/nodeId.properties
14:17:04.332 INFO [general]  rocksdb key-value data source created: peers
14:17:04.345 INFO [general]  External IP wasn't set, using checkip.amazonaws.com to identify it...
14:17:04.799 INFO [general]  External address identified: 192.168.0.114
14:17:04.818 INFO [discover]  Pinging discovery nodes...
14:17:04.856 INFO [general]  rocksdb key-value data source created: blockchain

14:17:04.984 INFO [general]  EthereumJ node started: enode://c43d9c4970fa1f336723981e1113fa893f2a84a244d9b7da83545e99b0963f2d39d997bb0ff4f34c6b3c83e7a5caab16bc931ad7b821475ae9393bac0ae86344@192.168.0.114:0
14:17:04.991 INFO [general]  DB is empty - adding Genesis
14:17:05.115 INFO [general]  Genesis block loaded
14:17:05.134 INFO [general]  Bind address wasn't set, Punching to identify it...
14:17:05.199 INFO [general]  UDP local bound to: 192.168.0.114
14:17:05.199 ERROR [discover]  Discovery can't be started while listen port == 0
14:17:05.205 INFO [sync]  Sync Manager: ON
14:17:05.205 INFO [sync]  Initializing SyncManager.
14:17:05.210 INFO [sync]  FastSync: looking for best block number...
14:17:05.269 INFO [general]  Ethereum listener added
14:17:10.212 INFO [sync]  FastSync: waiting for at least 5 peers or 54 sec to select pivot block... (0 peers so far)
14:17:15.203 INFO [net]  TCP: Speed in/out 256b / 255b(sec), packets in/out 12/17, total in/out: 2Kb / 2Kb
14:17:15.203 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:17:15.206 INFO [sync]  Sync state: PivotBlock (9 of 60), last block #0, best known #0
14:17:15.214 INFO [sync]  FastSync: waiting for at least 5 peers or 49 sec to select pivot block... (0 peers so far)
14:17:20.216 INFO [sync]  FastSync: waiting for at least 5 peers or 44 sec to select pivot block... (0 peers so far)
14:17:25.202 INFO [net]  TCP: Speed in/out 187b / 183b(sec), packets in/out 9/12, total in/out: 4Kb / 4Kb
14:17:25.203 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:17:25.205 INFO [sync]  Sync state: PivotBlock (19 of 60), last block #0, best known #0
14:17:25.217 INFO [sync]  FastSync: waiting for at least 5 peers or 39 sec to select pivot block... (0 peers so far)
14:17:30.219 INFO [sync]  FastSync: waiting for at least 5 peers or 34 sec to select pivot block... (0 peers so far)
14:17:35.202 INFO [net]  TCP: Speed in/out 187b / 183b(sec), packets in/out 9/12, total in/out: 6Kb / 6Kb
14:17:35.202 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:17:35.205 INFO [sync]  Sync state: PivotBlock (29 of 60), last block #0, best known #0
14:17:35.206 INFO [sync]  Peer stats:
Active peers
============
Other connected peers
============

14:17:35.206 INFO [sync]  

14:17:35.220 INFO [sync]  FastSync: waiting for at least 5 peers or 29 sec to select pivot block... (0 peers so far)
14:17:40.222 INFO [sync]  FastSync: waiting for at least 5 peers or 24 sec to select pivot block... (0 peers so far)
14:17:45.202 INFO [net]  TCP: Speed in/out 250b / 255b(sec), packets in/out 12/17, total in/out: 8Kb / 8Kb
14:17:45.202 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:17:45.205 INFO [sync]  Sync state: PivotBlock (39 of 60), last block #0, best known #0
14:17:45.223 INFO [sync]  FastSync: waiting for at least 5 peers or 19 sec to select pivot block... (0 peers so far)
14:17:50.225 INFO [sync]  FastSync: waiting for at least 5 peers or 14 sec to select pivot block... (0 peers so far)
14:17:55.202 INFO [net]  TCP: Speed in/out 250b / 244b(sec), packets in/out 12/16, total in/out: 11Kb / 10Kb
14:17:55.202 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:17:55.205 INFO [sync]  Sync state: PivotBlock (49 of 60), last block #0, best known #0
14:17:55.227 INFO [sync]  FastSync: waiting for at least 5 peers or 9 sec to select pivot block... (0 peers so far)
14:18:00.228 INFO [sync]  FastSync: waiting for at least 5 peers or 4 sec to select pivot block... (0 peers so far)
14:18:05.202 INFO [net]  TCP: Speed in/out 194b / 194b(sec), packets in/out 9/13, total in/out: 12Kb / 12Kb
14:18:05.202 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:18:05.205 INFO [sync]  Sync state: PivotBlock (59 of 60), last block #0, best known #0
14:18:05.206 INFO [sync]  Peer stats:
Active peers
============
Other connected peers
============

14:18:05.206 INFO [sync]  

14:18:05.230 INFO [sync]  FastSync: waiting for at least 5 peers or 0 sec to select pivot block... (0 peers so far)
14:18:10.231 INFO [sync]  FastSync: waiting for at least 5 peers or -5 sec to select pivot block... (0 peers so far)
14:18:15.202 INFO [net]  TCP: Speed in/out 250b / 255b(sec), packets in/out 12/17, total in/out: 15Kb / 15Kb
...
```

Why ethereumj not found my private node?

**Comment by mkalinin** [comment]
Could you please paste config and logs to some resource like pastebin to make it readable

**Comment by mkalinin** [comment]
Can you just remove `listen.port = 0` from your configuration. `discovery.enabled = false` definition is pretty enough. and a question: why do you need to disabled `eip8` handshake format? This option was added for test causes

**Comment by vachrushev** [comment]
I remove `listen.port = 0 ` from my ethereumj.conf and change `peer.p2p.eip8` configuration from false to true.
```
peer = {
    discovery.enabled = false
    active = [
        {url = "enode://f43e4c5d672d3054786aa5eb4e7efe9bcb41d9b5faa6858dd0176d516c37373f56e073b71e0b80ec487b29d087e9e747eb5d76c80b9cfb7c626c047f8f0fa1e6@192.168.0.114:30303"}
      ]
}
peer.networkId = 8690
peer.p2p.eip8 = true
blockchain.config.name = "testnet"
database {
    dir = database-parity
}
peer.discovery.enabled = true
database.reset = false
sync.enabled = true
sync.fast.enabled = true
keyvalue.datasource = rocksdb
```

But in logs added error:
```
4:52:50.882 INFO [sync]  Sync Manager: ON
14:52:50.882 INFO [sync]  Initializing SyncManager.
14:52:50.893 INFO [sync]  FastSync: looking for best block number...
14:52:50.932 INFO [net]  Listening for incoming connections, port: [30303] 
14:52:50.933 INFO [net]  NodeId: [42a9a7f9df07966bbfdfae9b921e3951e2792508590689cc79e7879133883aa063870b1b221a02d9082c5cd20d4e54f9dbc9850ce523c2d02c727fee50cae237] 
14:52:50.986 ERROR [net]  Peer server error: Address already in use (java.net.BindException)
14:52:50.990 ERROR [discover]  Port 30303 is busy. Check if another instance is running with the same port.
14:52:51.064 ERROR [general]  Uncaught exception
java.lang.Error: Server Disconnected
	at org.ethereum.net.server.PeerServer.start(PeerServer.java:111)
	at org.ethereum.net.server.ChannelManager.lambda$new$1(ChannelManager.java:116)
	at java.lang.Thread.run(Thread.java:745)
14:52:51.139 INFO [general]  Ethereum listener added
14:52:55.894 INFO [sync]  FastSync: waiting for at least 5 peers or 54 sec to select pivot block... (0 peers so far)
```

And peers also empty:
```
14:52:55.894 INFO [sync]  FastSync: waiting for at least 5 peers or 54 sec to select pivot block... (0 peers so far)
14:53:00.843 INFO [net]  TCP: Speed in/out 313b / 329b(sec), packets in/out 12/17, total in/out: 3Kb / 3Kb
14:53:00.843 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:53:00.872 INFO [sync]  Sync state: PivotBlock (9 of 60), last block #0, best known #0
14:53:00.896 INFO [sync]  FastSync: waiting for at least 5 peers or 49 sec to select pivot block... (0 peers so far)
14:53:05.898 INFO [sync]  FastSync: waiting for at least 5 peers or 44 sec to select pivot block... (0 peers so far)
14:53:10.843 INFO [net]  TCP: Speed in/out 234b / 222b(sec), packets in/out 9/12, total in/out: 5Kb / 5Kb
14:53:10.843 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:53:10.871 INFO [sync]  Sync state: PivotBlock (19 of 60), last block #0, best known #0
14:53:10.899 INFO [sync]  FastSync: waiting for at least 5 peers or 39 sec to select pivot block... (0 peers so far)
14:53:15.901 INFO [sync]  FastSync: waiting for at least 5 peers or 34 sec to select pivot block... (0 peers so far)
14:53:20.842 INFO [net]  TCP: Speed in/out 236b / 249b(sec), packets in/out 9/12, total in/out: 7Kb / 7Kb
14:53:20.843 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:53:20.871 INFO [sync]  Sync state: PivotBlock (29 of 60), last block #0, best known #0
14:53:20.889 INFO [sync]  Peer stats:
Active peers
============
Other connected peers
============

14:53:20.889 INFO [sync]  

14:53:20.902 INFO [sync]  FastSync: waiting for at least 5 peers or 29 sec to select pivot block... (0 peers so far)
14:53:25.904 INFO [sync]  FastSync: waiting for at least 5 peers or 24 sec to select pivot block... (0 peers so far)
14:53:30.842 INFO [net]  TCP: Speed in/out 310b / 316b(sec), packets in/out 12/16, total in/out: 10Kb / 10Kb
14:53:30.843 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:53:30.871 INFO [sync]  Sync state: PivotBlock (39 of 60), last block #0, best known #0
14:53:30.906 INFO [sync]  FastSync: waiting for at least 5 peers or 19 sec to select pivot block... (0 peers so far)
14:53:35.907 INFO [sync]  FastSync: waiting for at least 5 peers or 14 sec to select pivot block... (0 peers so far)
14:53:40.842 INFO [net]  TCP: Speed in/out 319b / 313b(sec), packets in/out 12/16, total in/out: 13Kb / 13Kb
14:53:40.843 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:53:40.871 INFO [sync]  Sync state: PivotBlock (49 of 60), last block #0, best known #0
14:53:40.909 INFO [sync]  FastSync: waiting for at least 5 peers or 9 sec to select pivot block... (0 peers so far)
14:53:45.910 INFO [sync]  FastSync: waiting for at least 5 peers or 4 sec to select pivot block... (0 peers so far)
14:53:50.842 INFO [net]  TCP: Speed in/out 238b / 235b(sec), packets in/out 9/12, total in/out: 16Kb / 16Kb
14:53:50.843 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
14:53:50.871 INFO [sync]  Sync state: PivotBlock (59 of 60), last block #0, best known #0
14:53:50.889 INFO [sync]  Peer stats:
Active peers
============
Other connected peers
============
```

**Comment by mkalinin** [comment]
Now you need to set `peer.listen.port` to some else value

**Comment by vachrushev** [comment]
When I remove peer.listen.port in logs message:
```
5:14:54.098 DEBUG [net]  auth exchange done
15:14:54.098 DEBUG [net]  To:   /192.168.0.114:30303    Send:  [HELLO p2pVersion=5 clientId=Ethereum(J)/v1.8.1/Linux/Release/Java/Dev capabilities=[eth:62 eth:63] peerPort=30303 peerId=8b0206bbf25a0e753ed285b524bb9c43eadc3a86f44f168e0d9cfa37781857c459f62ac3ff24f34690704df11fdc6644af62d01f7d9c6ae9fb48ed6a889006d4]
15:14:54.098 DEBUG [net]  From: /192.168.0.114:30303    Recv:  [HELLO p2pVersion=5 clientId=Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2 capabilities=[par:1 par:2 par:3 eth:62 eth:63 pip:1] peerPort=30303 peerId=f43e4c5d672d3054786aa5eb4e7efe9bcb41d9b5faa6858dd0176d516c37373f56e073b71e0b80ec487b29d087e9e747eb5d76c80b9cfb7c626c047f8f0fa1e6]
15:14:54.098 DEBUG [net]  publicRLPxHandshakeFinished with /192.168.0.114:30303
15:14:54.098 DEBUG [net]  [id: 0x15e63d70, /192.168.0.114:40000 => /192.168.0.114:30303]: use snappy compression
15:14:54.098 DEBUG [net]  P2P protocol activated
15:14:54.099 DEBUG [net]  EthV63 [ address = /192.168.0.114:30303 | id = f43e4c5d ]
15:14:54.099 DEBUG [net]  ETH protocol activated
15:14:54.099 DEBUG [net]  From: f43e4c5d | /192.168.0.114:30303    Recv:  [PING]
15:14:54.099 DEBUG [net]  To:   f43e4c5d | /192.168.0.114:30303    Send:  [PONG]
15:14:54.099 DEBUG [net]  From: f43e4c5d | /192.168.0.114:30303    Recv:  [STATUS protocolVersion=63 networkId=8690 totalDifficulty=020000 bestHash=586817cd17aa2108693836adcacb3b5376b981361484bce8c021f2ca46a480b6 genesisHash=586817cd17aa2108693836adcacb3b5376b981361484bce8c021f2ca46a480b6]
15:14:54.099 DEBUG [net]  Removing EthHandler for /192.168.0.114:30303 due to protocol incompatibility
15:14:54.099 DEBUG [net]  To:   f43e4c5d | /192.168.0.114:30303    Send:  [DISCONNECT reason=INCOMPATIBLE_PROTOCOL]
15:14:54.099 DEBUG [net]  Peer f43e4c5d | /192.168.0.114:30303: notifies about disconnect
15:14:54.100 DEBUG [net]  handlerRemoved: kill timers in EthHandler
15:14:54.100 DEBUG [net]  channel inactive: 
15:14:54.100 DEBUG [net]  channel inactive: 
```
When I add `peer.listen.port=30304` in log message:
```
15:16:56.854 DEBUG [net]  auth exchange done
15:16:56.854 DEBUG [net]  To:   /176.197.245.208:30307    Send:  [HELLO p2pVersion=5 clientId=Ethereum(J)/v1.8.1/Linux/Release/Java/Dev capabilities=[eth:62 eth:63] peerPort=30304 peerId=d2a734a0476812595c94c6f36541f1a4e90cf4f0607d67e68904353714f44d3ca17aa94cff42c2e7668767935e3d3206cb461d803d17626a3ce2341468a373be]
15:16:56.854 DEBUG [net]  From: 2c55fe73 | /176.197.245.208:30307    Recv:  [DISCONNECT reason=TOO_MANY_PEERS]
15:16:56.854 DEBUG [net]  Connection is closed
15:16:56.854 DEBUG [discover]  Terminated node connection: NodeHandler[state: Alive, node: 176.197.245.208:30307, id=2c55fe73]
15:16:56.854 DEBUG [discover]  Trying node connection: NodeHandler[state: Alive, node: 88.150.184.138:30303, id=32db93d5]
```

176.197.245.208:30307 this is not my IP

**Comment by mkalinin** [comment]
Is peer discovery disabled by `peer.discovery.enabled = false` option in your config? if no, then you should disabled it to prevent your peer from looking for each others in the net.

**Comment by mkalinin** [comment]
did it help?

**Comment by vachrushev** [comment]
This option `peer.discovery.enabled` disabled. 
My mistake in genesis file, genesis in app and parity not equals and peer not connected. 
I found log line in org.ethereum.net.eth.handler.Eth62.java:
```
protected synchronized void processStatus(StatusMessage msg, ChannelHandlerContext ctx) throws InterruptedException {

        try {

            if (!Arrays.equals(msg.getGenesisHash(), config.getGenesis().getHash())) {
                if (!peerDiscoveryMode) {
                    loggerNet.debug("Removing EthHandler for {} due to protocol incompatibility", ctx.channel().remoteAddress());
                }
                ethState = EthState.STATUS_FAILED;
                disconnect(ReasonCode.INCOMPATIBLE_PROTOCOL);
                ctx.pipeline().remove(this); // Peer is not compatible for the 'eth' sub-protocol
                return;
            }

            if (msg.getNetworkId() != config.networkId()) {
                ethState = EthState.STATUS_FAILED;
                disconnect(ReasonCode.NULL_IDENTITY);
                return;
            }

            // basic checks passed, update statistics
            channel.getNodeStatistics().ethHandshake(msg);
            ethereumListener.onEthStatusUpdated(channel, msg);

            if (peerDiscoveryMode) {
                loggerNet.trace("Peer discovery mode: STATUS received, disconnecting...");
                disconnect(ReasonCode.REQUESTED);
                ctx.close().sync();
                ctx.disconnect().sync();
                return;
            }

            // update bestKnownBlock info
            sendGetBlockHeaders(msg.getBestHash(), 1, 0, false);

        } catch (NoSuchElementException e) {
            loggerNet.debug("EthHandler already removed");
        }
    }
``

Mikhail, thanks for the help.

**Comment by mkalinin** [comment]
ok, nice 👍 you're welcome!
