### ISSUE TITLE
NullPointer when query new account.getBalance().

### ISSUE THREAD

**Issue by Bitcoinzie** [ethereum/ethereumj#217]
Using the method below we add the existing accounts from the users wallet to an arraylist named acList. Then we add a new account using "wallet.addNewAccount()". Then we reload the arraylist and grab the new account testing it for a balance, which should be zero at this point. 
What we get is a nullpointer. However if instead of "account.getBalance()" we use " ethereum.getRepository().getBalance(ac.getAddress())" we see that the balance at this account is zero, no nullpointer.  

 "Exception in thread "main" java.lang.NullPointerException
	at org.ethereum.core.Account.getBalance(Account.java:57)
	at eth.EthNull.main(EthNull.java:61)"

```
public class EthNull {
    
   public static final Ethereum ethereum =  EthereumFactory.createEthereum();
    private static final String ip = "5.1.83.141";
    private static final int port = 30303;
    private static final Wallet wallet = ethereum.getWallet();
    private static final Repository repository = ethereum.getRepository();
    private static final ArrayList acntList = new ArrayList<>();
    private static Account account;
    
    public static void main(String[] args) throws IOException, InterruptedException {
        
        SwingUtilities.invokeLater(() -> {
            ethereum.connect(ip, port);
        });
        ArrayList<Account> acList = wallet();
        addNew();
        acList = wallet();
        Account ac = acList.get(2);
        /* "ac.getBalance()" causes NullPointer, but:
        ethereum.getRepository().getBalance(ac.getAddress())
        Does not. 
        */
        ac.getBalance();
    }
    
    public static ArrayList<Account> wallet(){
        for(Iterator<Account> it = wallet.getAccountCollection().iterator(); it.hasNext();) {
            account = it.next();
            System.out.println(account);
             if(!acntList.contains(account))
                 acntList.add(account);
        }
        return acntList;
    }
    
    /**
     *
     * Adds new account to the users wallet
     */
    public static void addNew() {
        wallet.addNewAccount();
    }
    
}
```

**Comment by romanman** [comment]
interesting what address is this ?

**Comment by Bitcoinzie** [comment]
The address should be random each time, as I have the DB reset each time, but if you add this line 
```
System.out.println(Hex.toHexString(ac.getEcKey().getAddress()));
```
It will print the address.

**Comment by Bitcoinzie** [comment]
To explain further the addNew() method calls "core.wallet.addNewAccount()" 
```
 public void addNewAccount() {
        Account account = new Account();
        account.init();
```
Which calls "core.Account.init()" with no arguments.
in this init function the address is generated randomly.
```
public void init() {
        this.ecKey = new ECKey(Utils.getRandom());
        address = this.ecKey.getAddress();
    }
```
