### ISSUE TITLE
java.lang.Error: Unknown RLPx message

### ISSUE THREAD

**Issue by mikkazan** [ethereum/ethereumj#307]
Hi Ethereum people,
Had to work on something else and now back to ethereumJ :)
I have 2 ethereumJ instances running on 2 different machines. I wrote code to connect them with each other, but after I execute this line 

```
ethereumBean.getEthereum().connect(connection.getServerIp(), connection.getServerPort(), connection.getServerId());
```

In serverId I am passing NodeId which I got from the log file,

Immediately I see the exception on the machine I'm trying to connect to -
2015-09-15 12:17:01.968 ERROR 11316 --- [ntLoopGroup-4-1] net                                      : MessageCodec handling failed

```
io.netty.handler.codec.DecoderException: org.spongycastle.util.encoders.EncoderException: exception encoding Hex string: 0
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:358)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.spongycastle.util.encoders.EncoderException: exception encoding Hex string: 0
        at org.spongycastle.util.encoders.Hex.encode(Hex.java:60)
        at org.spongycastle.util.encoders.Hex.toHexString(Hex.java:27)
        at org.ethereum.net.rlpx.discover.NodeHandler.toString(NodeHandler.java:270)
        at java.lang.String.valueOf(String.java:2982)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at org.ethereum.net.rlpx.discover.NodeHandler.sendPing(NodeHandler.java:224)
        at org.ethereum.net.rlpx.discover.NodeHandler.changeState(NodeHandler.java:118)
        at org.ethereum.net.rlpx.discover.NodeHandler.<init>(NodeHandler.java:86)
        at org.ethereum.net.rlpx.discover.NodeManager.getNodeHandler(NodeManager.java:202)
        at org.ethereum.net.rlpx.discover.NodeManager.getNodeStatistics(NodeManager.java:219)
        at org.ethereum.net.server.Channel.getNodeStatistics(Channel.java:183)
        at org.ethereum.net.rlpx.MessageCodec.decodeHandshake(MessageCodec.java:238)
        at org.ethereum.net.rlpx.MessageCodec.decode(MessageCodec.java:83)
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
        ... 19 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.spongycastle.util.encoders.HexEncoder.encode(HexEncoder.java:62)
        at org.spongycastle.util.encoders.Hex.encode(Hex.java:56)
        ... 33 common frames omitted


later it appears that servers are keep trying to connect to each other but keep failing with this error

java.lang.Error: Unknown RLPx message
        at org.ethereum.net.rlpx.Message.decode(Message.java:49)
        at org.ethereum.net.rlpx.discover.PacketDecoder.decode(PacketDecoder.java:22)
        at org.ethereum.net.rlpx.discover.PacketDecoder.decode(PacketDecoder.java:14)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

Am I missing something in my config? BTW, I commented out privateKey in ethereumj.conf hoping that upon start it will generate unique nodeId, but nodeId is the same on both servers for some reason. Could you tell me how I can fix these issues?

**Comment by romanman** [comment]
@mikkazan : thanks we will check it, 
what version of ethereumj are you using ?

**Comment by mikkazan** [comment]
this one https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/repo/org/ethereum/ethereumj-core/1.0.0-RC1

**Comment by Nashatyrev** [comment]
@mikkazan 
Can you try the latest `develop` snapshot plz: https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/repo/org/ethereum/ethereumj-core/1.0.0-SNAPSHOT

**Comment by mikkazan** [comment]
Not a trivial task in my company:). I will try to get that version.

**Comment by romanman** [comment]
@mikkazan : why not trivial?
curious.?

**Comment by mikkazan** [comment]
Much better. Errors are gone. I can connect and see peers. I am not sure if this is this issue or no
but on both servers I see nodeId as this. Is it mandatory to have privateKey in .conf file and If i want nodeIds on the different servers to be unique should I generate private key for each server myself?

Machine1
dead745c1dbcde518b48e52aca1e8d5ba666005a2c8804e39826c6080fb11c1e8abe41d1e41896e871f204f790a90fa9781744cccecf492212192a7c56e7673b
Machine2
dead745c1dbcde518b48e52aca1e8d5ba666005a2c8804e39826c6080fb11c1e8abe41d1e41896e871f204f790a90fa9781744cccecf492212192a7c56e7673b

**Comment by mikkazan** [comment]
@romanman All external maven repos are banned in our company. Managed to get zip ripped off jar out of there and then installed it to my local repo :)

**Comment by romanman** [comment]
@mikkazan , got you so just pull the latest version out of SNAPSHOT folder

**Comment by mikkazan** [comment]
@romanman 
What about my last question regarding same nodeId on both machines?

**Comment by romanman** [comment]
@mikkazan so node id is basically, the public key for the private key you specify, and private key is just arbitrary set of bytes, so pick any you want

**Comment by mikkazan** [comment]
Understood, thanks. Would be much better if you did the same way like it's done in geth. In geth client we do not specify any private key at all and nodeid is different on all machines which are running in the network.

**Comment by romanman** [comment]
@mikkazan : yeah they do it random generated, 
so we decided to make it more controlled
maybe we should make it random if not specified

**Comment by Nashatyrev** [comment]
@mikkazan You may just run the following code: 
```
        ECKey k = new ECKey().decompress();
        System.out.println("NodeID: " + Hex.toHexString(k.getPubKey()).substring(2));
        System.out.println("PrivKey: " + Hex.toHexString(k.getPrivKeyBytes()));
```
In case you don't care, I've generated a couple for you :)
```NodeID: 4000e12b9b4f9e8ac0a9cdb48e06a987388385ae2c3f07a665033cdc0ec23c1622ad63cdb9259d10f49402ab86b48aaea5f0312c54f6b7aa2a5135c3092df3ba
PrivKey: 9c6a686741995ba1d8263d3fa0ddfe64b37984688e4872e6ffe11c69c766c12d
NodeID: 49aa613ce1dd3eeee1677c4a6f1e46dc7f04126b1762210420199488ef319c8a62a302b27eafdb474c0f89b38ebbb9491e1d6316c2d09bdf3a4e2313b9670336
PrivKey: fbf7b6e71f553693a5a4c0d0f8a3b38aea2d1646a9c3973a15c6bf295c5f494e
```
