### ISSUE TITLE
NullPOinterException in Channel.getPeerId

### ISSUE THREAD

**Issue by mikkazan** [ethereum/ethereumj#310]
Hi EtheruemJ team,
Started ethereumJ on 3 server cluster. Connected each other and now periodically on one server I see this exception

java.lang.NullPointerException: null
	at org.ethereum.net.server.Channel.getPeerId(Channel.java:221)
	at org.ethereum.net.eth.sync.PeersPool.onDisconnect(PeersPool.java:121)
	at org.ethereum.net.eth.sync.SyncManager.onDisconnect(SyncManager.java:185)
	at org.ethereum.net.server.ChannelManager.notifyDisconnect(ChannelManager.java:97)
	at org.ethereum.net.server.EthereumChannelInitializer$1.operationComplete(EthereumChannelInitializer.java:63)
	at org.ethereum.net.server.EthereumChannelInitializer$1.operationComplete(EthereumChannelInitializer.java:59)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:406)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:956)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:608)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:586)

2 servers are remote Linux servers and one server is my local Windows machine. It happens on my Windows machine so far

**Comment by mkalinin** [comment]
@mikkazan we have already fixed that. The fix will appear in develop branch soon ;)

**Comment by mikkazan** [comment]
Okey dokey :)
