### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by mikkazan** [ethereum/ethereumj#314]
Hi guys,
periodically I see ConectionException on the server to which one of the node connected to.

java.net.ConnectException: Connection refused: /my_local_ip:52062
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at java.lang.Thread.run(Thread.java:745)

Then it re-establish the connection until it fails next time. What can cause it? I understand that port is busy probably because of many block exchanges between 2 nodes. 
One more question - 
I see this a lot in the logs

server2
15-09-29 13:20:07.493  INFO 11661 --- [JClientWorker-0] net                                      : To:        server1/server1_ip:30303      Send:   [BLOCK_HASHES[]](0)
2015-09-29 13:20:07.520  INFO 11661 --- [JClientWorker-0] net                                      : From:      server1/server1_ip:30303      Recv:   [GET_BLOCK_HASHES_BY_NUMBER blockNumber=353 maxBlocks=10000]
2015-09-29 13:20:07.523  INFO 11661 --- [JClientWorker-0] net                                      : To:        server1/server1_ip:30303      Send:   [BLOCK_HASHES[]](0)
2015-09-29 13:20:07.549  INFO 11661 --- [JClientWorker-0] net                                      : From:      server1/server1_ip:30303      Recv:   [GET_BLOCK_HASHES_BY_NUMBER blockNumber=354 maxBlocks=10000]
2015-09-29 13:20:07.553  INFO 11661 --- [JClientWorker-0] net                                      : To:        server1/server1_ip:30303      Send:   [BLOCK_HASHES[]](0)
2015-09-29 13:20:07.578  INFO 11661 --- [JClientWorker-0] net                                      : From:      server1/server1_ip:30303      Recv:   [GET_BLOCK_HASHES_BY_NUMBER blockNumber=355 maxBlocks=10000]
2015-09-29 13:20:07.583  INFO 11661 --- [JClientWorker-0] net                                      : To:        server1/server1_ip:30303      Send:   [BLOCK_HASHES[]](0)
2015-09-29 13:20:07.608  INFO 11661 --- [JClientWorker-0] net                                      : From:      server1/server1_ip:30303      Recv:   [GET_BLOCK_HASHES_BY_NUMBER blockNumber=356 maxBlocks=10000]
2015-09-29 13:20:07.613  INFO 11661 --- [JClientWorker-0] net                                      : To:        server1/server1_ip:30303      Send:   [BLOCK_HASHES[]](0)

server1
Blocks=10000]
2015-09-29 13:21:37.252  INFO 3093 --- [ntLoopGroup-4-1] net                                      : To:         server2/server2_ip:38534      Send:   [GET_BLOCK_HASHES_BY_NUMBER blockNumber=3069 maxBlocks=10000]
2015-09-29 13:21:37.259  INFO 3093 --- [ntLoopGroup-4-1] net                                      : To:         my_local/my_local_ip:52060     Send:   [BLOCK_HASHES[]](0)
2015-09-29 13:21:37.271  INFO 3093 --- [ntLoopGroup-4-1] net                                      : From:       server2/server2_ip:38534      Recv:   [BLOCK_HASHES 04...04](1)
2015-09-29 13:21:37.275  INFO 3093 --- [ntLoopGroup-4-1] blockqueue                               : Block hashes list size: [112]
2015-09-29 13:21:37.279  INFO 3093 --- [ntLoopGroup-4-1] net                                      : To:         server2/server2_ip:38534      Send:   [GET_BLOCK_HASHES_BY_NUMBER blockNumber=3070 maxBlocks=10000]
2015-09-29 13:21:37.301  INFO 3093 --- [ntLoopGroup-4-1] net                                      : From:       server2/server2_ip:38534      Recv:   [BLOCK_HASH

And logs are moving constantly. Is it expected behavior as well?

**Comment by mikkazan** [comment]
last question regarding contract submission. How can I retrieve contract info. I cannot find any docs about it.

**Comment by mkalinin** [comment]
hey @mikkazan 
`my_local_ip:52062` - does this mean that you're connected to some local peer?

**Comment by mikkazan** [comment]
Yeah, I have 2 remote Linux servers running ethereumj and third one is my local host

**Comment by mkalinin** [comment]
ok, thanks. will investigate in it

**Comment by mkalinin** [comment]
Usually this error occurs during connection establishing. Is it your case? If not could you please share more logs and provide more details about this error occurring?

**Comment by mikkazan** [comment]
Unfortunately I did not save the logs. Did not set up process to print into the log file. It happens after connection established. Looks like port periodically becomes busy may be because of constant blocks exchange.

**Comment by mikkazan** [comment]
Looks like I am being pulled off from java implementation back to go. I will let you know once I'll be back :).
