### ISSUE TITLE
Exception in the NodeManagerListenerHandler by enabling the peer discovery

### ISSUE THREAD

**Issue by skydogch** [ethereum/ethereumj#319]
Hi guys,

I am using the latest snapshot and I am connecting ethereumj to my local geth peer.

I have noticed that when I disable the peer discovery in the configuration, then the connection to my local peer works fine, but when I turn the discovery on, then I get an exception in the NodeManagerListenerHandler

**"Exception processing listener: org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler@6fa3d735"**

-------------------------------------------------------------------

22:33:37.539 INFO  general - Running frontier-custom.json,  core version: 1.0.0-SNAPSHOT
22:33:37.569 INFO  general - git.hash: [fedd876]
22:33:37.570 INFO  general - build.time: [GMT]-[14/Oct/2015]-[19:03]
22:33:37.570 INFO  general - 
22:33:37.572 INFO  general - Database reset done
22:33:37.574 INFO  general - capability eth version: [60, 61]
22:33:37.576 INFO  general - capability shh version: [2]
22:33:37.576 INFO  general - capability bzz version: [0]
22:33:37.921 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@55bbdbbd: startup date [Wed Oct 14 22:33:37 CEST 2015]; root of context hierarchy
22:33:40.708 INFO  o.s.b.f.s.DefaultListableBeanFactory - Overriding bean definition for bean 'blockStore': replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=remoteConfig; factoryMethodName=blockStore; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/ethereum/config/RemoteConfig.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=defaultConfig; factoryMethodName=blockStore; initMethodName=null; destroyMethodName=(inferred); defined in org.ethereum.config.DefaultConfig]
22:33:41.607 INFO  general - External IP wasn't set, using checkip.amazonaws.com to identify it...
22:33:41.961 INFO  general - External address identified: 
.187.106.145
22:33:42.199 INFO  general - In memory 'pendingTransactions' storage created.
22:33:42.263 INFO  general - leveldb key-value data source created.
22:33:42.273 INFO  general - leveldb key-value data source created.

22:33:44.788 INFO  general - Ethereum listener added
22:33:44.918 INFO  general - DB is empty - adding Genesis
22:33:45.632 INFO  general - Genesis block loaded
22:33:45.641 INFO  blockqueue - Start loading sync queue
22:33:45.645 INFO  general - Bind address wasn't set, Punching to identify it...
22:33:45.686 INFO  sync - Sync Manager: ON
22:33:45.774 INFO  net - Listening for incoming connections, port: [30305] 
22:33:45.794 INFO  net - NodeId: [fe3fd3bfd5595ea43605cdd896b6eed514322018b4c241ce4a206da8d23ec95e15daeff131c2e65434b14034645911d65ab34c1e9155c1febaef702b9cc0f0f4] 
22:33:45.857 INFO  blockqueue - Hash store loaded, size [0]
22:33:45.942 INFO  blockqueue - Block queue loaded, size [0]
22:33:45.952 INFO  sync - Changing state from IDLE to HASH_RETRIEVING
22:33:45.956 INFO  facade - Connecting to: 127.0.0.1:30303
22:33:46.012 INFO  sync - 

22:33:46.013 INFO  sync - State HASH_RETRIEVING

22:33:46.087 INFO  net - Open connection, channel: [id: 0xdfce9f8d]
22:33:55.670 WARN  general - Can't get bind IP. Fall back to 0.0.0.0: java.net.UnknownHostException: www.google.com
22:33:55.700 INFO  discover - Discovery UDPListener started
22:33:55.917 INFO  general - Connecting to the block store
22:33:55.923 INFO  o.s.j.d.DriverManagerDataSource - Loaded JDBC driver: org.h2.Driver
22:33:56.009 INFO  general - Ethereum listener added
test
22:33:56.231 INFO  net - Open connection, channel: [id: 0x6b92238f]
22:33:56.327 INFO  net - RLPX protocol activated
22:33:56.358 INFO  net - Open connection, channel: [id: 0xc14509d1]
22:33:56.462 INFO  net - RLPX protocol activated
22:33:56.638 INFO  net - To: 	localhost/127.0.0.1:30303 	Send: 	AuthInitiateMessage{
  sigBytes=c8484bda3fb70b7556929f4c81eab0c25d99e8f2f091e158a23c3676e35c7b7cd8320c6ed67defb4547f69154a9866f4d64ba8d7ea0f6f86b43a6f5137fe5a00
  ephemeralPublicHash=9b7ed7b6ca772c7f45c52e48c053871fe05dbac9a7c2c69b427dfefbfe0c2149
  publicKey=04fe3fd3bfd5595ea43605cdd896b6eed514322018b4c241ce4a206da8d23ec95e15daeff131c2e65434b14034645911d65ab34c1e9155c1febaef702b9cc0f0f4
  nonce=02c782d37744262cca58741493b16d432c195b8716bef2f50a00a103f8fd21d1
}
22:33:56.641 INFO  net - To: 	localhost/127.0.0.1:30303 	Send: 	AuthInitiateMessage{
  sigBytes=e2f99a51b620730dfb92dc5ca1d87b0743bfc6c1959adebc2b6071152027b05f1d1b8e0bc9fcc898f95a92133f4cc37362186322c0109bdbb6ff33c14a03355800
  ephemeralPublicHash=c3cf8e43190152a5513eb4ae268e5f99342f8c2cf266f4443deb66ac94363238
  publicKey=047f2bd1bd7c1ef7912e28289258362557b0b15c131a76d5eedaaa583d056411e74c16e887a6d32e7f9be2d0f6c500b92542a8463f36744fb422ce8b781d929813
  nonce=1b5aa07905c1dfac096c0a6232b8d54091379919a94ad6e1979667eca8719f9c
}
22:33:56.767 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	AuthResponseMessage{
  ephemeralPublicKey=(2cb4a91b74d553528c5f2e611b8bc4b6ac850fc0199f948949eaa773a4882eb8,b599f60adb172c49d376b2247ab1e46439067e9a9ab163bd8275dd759dd033e1,1,0)
  nonce=505919c74390b96469ed6103169b97929ffbd22f3711bca4ba4af88a36024ae9
  isTokenUsed=false}
22:33:56.769 INFO  net - auth exchange done
22:33:56.788 INFO  net - To: 	localhost/127.0.0.1:30303 	Send: 	[HELLO p2pVersion=4 clientId=Ethereum(J)/v1.0.0/Dev/Linux/Java capabilities=[eth:60 eth:61] peerPort=9 peerId=7f2bd1bd7c1ef7912e28289258362557b0b15c131a76d5eedaaa583d056411e74c16e887a6d32e7f9be2d0f6c500b92542a8463f36744fb422ce8b781d929813]
22:33:56.813 INFO  wire - MessageCodec: Buffer bytes: 288
22:33:56.816 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[HELLO p2pVersion=4 clientId=Geth/v1.2.2/linux/go1.5 capabilities=[eth:62 eth:61] peerPort=0 peerId=8ffc7ef38d8aa38f5ec9cac58f286b41d2a811703a97a8edfe1e4cd412164755bf721654e3863741ff0721601bf3944190baf51973107971eba2444a0c84f9b7]
22:33:56.817 INFO  net - P2P protocol activated
22:33:56.939 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	AuthResponseMessage{
  ephemeralPublicKey=(fa8aae2dd2579bc3900a46e12fb9371b9adeb0c5e095922e7318c247d88026d5,8f3b303a899ba708b7ea8cbba4c2aa664d010497548985c6a81dfda010eb5823,1,0)
  nonce=6d0852f0be8de9b0a21807ac467a8e42a427c1e5b0bcb112ca72dffb85be4583
  isTokenUsed=false}
22:33:56.957 INFO  net - auth exchange done
22:33:56.965 INFO  net - To: 	localhost/127.0.0.1:30303 	Send: 	[HELLO p2pVersion=4 clientId=Ethereum(J)/v1.0.0/Dev/Linux/Java capabilities=[eth:60 eth:61] peerPort=30305 peerId=fe3fd3bfd5595ea43605cdd896b6eed514322018b4c241ce4a206da8d23ec95e15daeff131c2e65434b14034645911d65ab34c1e9155c1febaef702b9cc0f0f4]
22:33:56.966 INFO  wire - MessageCodec: Buffer bytes: 160
22:33:56.967 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[HELLO p2pVersion=4 clientId=Geth/v1.2.2/linux/go1.5 capabilities=[eth:62 eth:61] peerPort=0 peerId=8ffc7ef38d8aa38f5ec9cac58f286b41d2a811703a97a8edfe1e4cd412164755bf721654e3863741ff0721601bf3944190baf51973107971eba2444a0c84f9b7]
22:33:56.968 INFO  net - P2P protocol activated
22:33:56.984 INFO  net - EthV61 [ address = localhost/127.0.0.1:30303 | id = 8ffc7ef3 ]
22:33:56.984 INFO  net - ETH protocol activated
22:33:56.984 INFO  net - EthV61 [ address = localhost/127.0.0.1:30303 | id = 8ffc7ef3 ]
22:33:56.985 INFO  net - ETH protocol activated
22:33:57.002 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[STATUS protocolVersion=61 networkId=54321 totalDifficulty=0ff8aa33 bestHash=162b7359bafeabba7c802db9a37d6d5ba168b9d7409eb0ff46a761aecb2c48d0 genesisHash=8103ce849520fe3faa39a0e889b09cc228582d69aaea0eee2a2d29b1ae193672]
22:33:57.003 INFO  net - To: 	localhost/127.0.0.1:30303 	Send: 	[STATUS protocolVersion=61 networkId=54321 totalDifficulty=40 bestHash=8103ce849520fe3faa39a0e889b09cc228582d69aaea0eee2a2d29b1ae193672 genesisHash=8103ce849520fe3faa39a0e889b09cc228582d69aaea0eee2a2d29b1ae193672]
22:33:57.011 INFO  net - To: 	localhost/127.0.0.1:30303 	Send: 	[DISCONNECT reason=REQUESTED]
22:33:57.027 INFO  net - To: 	localhost/127.0.0.1:30303 	Send: 	[STATUS protocolVersion=61 networkId=54321 totalDifficulty=40 bestHash=8103ce849520fe3faa39a0e889b09cc228582d69aaea0eee2a2d29b1ae193672 genesisHash=8103ce849520fe3faa39a0e889b09cc228582d69aaea0eee2a2d29b1ae193672]
22:33:57.034 INFO  net - channel inactive: 
22:33:57.043 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[STATUS protocolVersion=61 networkId=54321 totalDifficulty=0ff8aa33 bestHash=162b7359bafeabba7c802db9a37d6d5ba168b9d7409eb0ff46a761aecb2c48d0 genesisHash=8103ce849520fe3faa39a0e889b09cc228582d69aaea0eee2a2d29b1ae193672]
22:33:57.370 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	NEW_BLOCK [ number: 1424 hash:217239 difficulty: 0ffca542 ]
22:33:57.378 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[NEW_BLOCK_HASHES 21723951784be1fc159e6f724c996b86fcef5e65d673c49ca7393483b705bc8a...21723951784be1fc159e6f724c996b86fcef5e65d673c49ca7393483b705bc8a] (1)
22:33:57.380 INFO  sync - New block received: block.index [1424]
22:33:57.427 INFO  blockqueue - Block hashes list size: [0]
22:33:57.434 INFO  blockqueue - BlockQueue size: 0
22:33:57.435 INFO  blockchain - Try connect block hash: 217239, number: 1424
22:33:57.452 INFO  blockqueue - No parent on the chain for block.number: 1424 block.hash: 217239
22:33:57.789 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	NEW_BLOCK [ number: 1425 hash:14f3a5 difficulty: 1000a0d0 ]
22:33:57.796 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[NEW_BLOCK_HASHES 14f3a556e39e1077bb1648c325edda705e1bd578234a61af1af9f3f2138a49f3...14f3a556e39e1077bb1648c325edda705e1bd578234a61af1af9f3f2138a49f3] (1)
22:33:57.799 INFO  sync - New block received: block.index [1425]
22:33:57.832 ERROR discover - Exception processing listener: org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler@6fa3d735
java.lang.ArithmeticException: BigInteger divide by zero
	at java.math.MutableBigInteger.divide(MutableBigInteger.java:883) ~[na:1.7.0_79]
	at java.math.BigInteger.divide(BigInteger.java:1342) ~[na:1.7.0_79]
	at org.ethereum.util.BIUtil.isIn20PercentRange(BIUtil.java:113) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:395) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:389) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler.checkAll(NodeManager.java:393) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.processListeners(NodeManager.java:340) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.access$000(NodeManager.java:35) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$2.run(NodeManager.java:112) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
	at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
22:33:57.837 INFO  blockqueue - Block hashes list size: [0]
22:33:58.562 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	NEW_BLOCK [ number: 1426 hash:7e1dc2 difficulty: 10049cdd ]
22:33:58.565 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[NEW_BLOCK_HASHES 7e1dc2dcfcda629b6af6145bc4a858fd059cf30c8a8142194147aa5e89f47c76...7e1dc2dcfcda629b6af6145bc4a858fd059cf30c8a8142194147aa5e89f47c76] (1)
22:33:58.567 INFO  sync - New block received: block.index [1426]
22:33:58.615 INFO  blockqueue - Block hashes list size: [0]
22:33:58.825 ERROR discover - Exception processing listener: org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler@6fa3d735
java.lang.ArithmeticException: BigInteger divide by zero
	at java.math.MutableBigInteger.divide(MutableBigInteger.java:883) ~[na:1.7.0_79]
	at java.math.BigInteger.divide(BigInteger.java:1342) ~[na:1.7.0_79]
	at org.ethereum.util.BIUtil.isIn20PercentRange(BIUtil.java:113) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:395) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:389) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler.checkAll(NodeManager.java:393) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.processListeners(NodeManager.java:340) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.access$000(NodeManager.java:35) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$2.run(NodeManager.java:112) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
	at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
22:33:58.978 INFO  net - To: 	localhost/127.0.0.1:30303 	Send: 	[PING]
22:33:58.995 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[PONG]
22:33:59.526 INFO  blockqueue - BlockQueue size: 2
22:33:59.528 INFO  blockchain - Try connect block hash: 217239, number: 1424
22:33:59.542 INFO  blockqueue - No parent on the chain for block.number: 1424 block.hash: 217239
22:33:59.732 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	NEW_BLOCK [ number: 1427 hash:63f1e7 difficulty: 10089969 ]
22:33:59.735 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[NEW_BLOCK_HASHES 63f1e7b8d9152b2d2c40feae44f41aadc9ec96608188b1bf460d3f8b53b5b46b...63f1e7b8d9152b2d2c40feae44f41aadc9ec96608188b1bf460d3f8b53b5b46b] (1)
22:33:59.737 INFO  sync - New block received: block.index [1427]
22:33:59.777 INFO  blockqueue - Block hashes list size: [0]
22:33:59.825 ERROR discover - Exception processing listener: org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler@6fa3d735
java.lang.ArithmeticException: BigInteger divide by zero
	at java.math.MutableBigInteger.divide(MutableBigInteger.java:883) ~[na:1.7.0_79]
	at java.math.BigInteger.divide(BigInteger.java:1342) ~[na:1.7.0_79]
	at org.ethereum.util.BIUtil.isIn20PercentRange(BIUtil.java:113) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:395) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:389) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler.checkAll(NodeManager.java:393) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.processListeners(NodeManager.java:340) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.access$000(NodeManager.java:35) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$2.run(NodeManager.java:112) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
	at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
22:34:00.825 ERROR discover - Exception processing listener: org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler@6fa3d735
java.lang.ArithmeticException: BigInteger divide by zero
	at java.math.MutableBigInteger.divide(MutableBigInteger.java:883) ~[na:1.7.0_79]
	at java.math.BigInteger.divide(BigInteger.java:1342) ~[na:1.7.0_79]
	at org.ethereum.util.BIUtil.isIn20PercentRange(BIUtil.java:113) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:395) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:389) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler.checkAll(NodeManager.java:393) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.processListeners(NodeManager.java:340) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.access$000(NodeManager.java:35) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$2.run(NodeManager.java:112) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
	at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
22:34:01.417 INFO  net - RLPX protocol activated
22:34:01.488 INFO  net - To: 	pub158181107145.dh-hfc.myip.com/158.181.107.145:30303 	Send: 	AuthInitiateMessage{
  sigBytes=412f5a7b50eb6c7dacdf017c605a3bb701d41b92ae0f36745720f7064fc41ca9758f9f44f756dc96f53997de57c132fb458d89ccb6208168a51a708d4f90598000
  ephemeralPublicHash=a7827e6a19625057512449981f5286fc4bb13f91983e45598eab048fb2d08fe0
  publicKey=049724ed5176977be5beb1dbcbbef9f5832a169705a1c53be23ed7a0de5b297bedfc0efe16bfd5ee5ea3428d81d8c02e9569aef569be81148d9282de2b1ecbbbe9
  nonce=6b24cef32a838a90d29b855ecfb92d1a965c4e6115ec17fe7c4ce0a51151e4a5
}
22:34:01.575 INFO  blockqueue - BlockQueue size: 3
22:34:01.593 INFO  blockchain - Try connect block hash: 217239, number: 1424
22:34:01.596 INFO  blockqueue - No parent on the chain for block.number: 1424 block.hash: 217239
22:34:01.825 ERROR discover - Exception processing listener: org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler@6fa3d735
java.lang.ArithmeticException: BigInteger divide by zero
	at java.math.MutableBigInteger.divide(MutableBigInteger.java:883) ~[na:1.7.0_79]
	at java.math.BigInteger.divide(BigInteger.java:1342) ~[na:1.7.0_79]
	at org.ethereum.util.BIUtil.isIn20PercentRange(BIUtil.java:113) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:395) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:389) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler.checkAll(NodeManager.java:393) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.processListeners(NodeManager.java:340) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager.access$000(NodeManager.java:35) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at org.ethereum.net.rlpx.discover.NodeManager$2.run(NodeManager.java:112) [ethereumj-core-1.0.0-SNAPSHOT.jar:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
	at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
22:34:02.087 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	NEW_BLOCK [ number: 1428 hash:5a4da6 difficulty: 100c9674 ]
22:34:02.099 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[NEW_BLOCK_HASHES 5a4da6bcd818fd358de6d7b352c5e0f354f8483dab36f56e4b5dbe1f0ff5f314...5a4da6bcd818fd358de6d7b352c5e0f354f8483dab36f56e4b5dbe1f0ff5f314] (1)
22:34:02.102 INFO  sync - New block received: block.index [1428]
22:34:02.170 INFO  blockqueue - Block hashes list size: [0]

**Comment by Nashatyrev** [comment]
@mkalinin Looks like yours:
at org.ethereum.util.BIUtil.isIn20PercentRange(BIUtil.java:113) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:395) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
at org.ethereum.net.eth.sync.SyncManager$3.test(SyncManager.java:389) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]
at org.ethereum.net.rlpx.discover.NodeManager$ListenerHandler.checkAll(NodeManager.java:393) ~[ethereumj-core-1.0.0-SNAPSHOT.jar:na]

**Comment by Nashatyrev** [comment]
Another strange thing: 
22:33:55.670 WARN general - Can't get bind IP. Fall back to 0.0.0.0: java.net.UnknownHostException: www.google.com
While checkip.amazonaws.com was resolved.

**Comment by Nashatyrev** [comment]
You may want to try to explicitly set the bind IP in the config: `peer.bind.ip` 
Set it to the outbound network interface IP.

**Comment by mkalinin** [comment]
@skydogch Division by zero is fixed now. Please, check it and close the issue if everything is well.

**Comment by skydogch** [comment]
Hi guys, perfect! It works! :+1:
