### ISSUE TITLE
repository.getNonce - BLOCK: STATE CONFLICT!

### ISSUE THREAD

**Issue by skydogch** [ethereum/ethereumj#327]
Hi guys,

I am getting a [block state](https://gist.github.com/skydogch/30d58f00b61f68b9ee69#file-block_conflict-L2662) conflict after executing [repository.getNonce](https://gist.github.com/skydogch/af29b9e9aae2662f529d#file-accountwritetest001-java-L45).

Please let me know if you need more information about this test case

````javascript
08:38:48.072 INFO  repository - updatingBatch: detailsCache.size: 0
08:38:48.072 INFO  repository - updated: detailsCache.size: 0
08:38:48.072 ERROR state - BLOCK: STATE CONFLICT! block: 11524 worldstate 8a0fbde94cf8cfb0ab3f4c8fdcff6db94010064987e2aad538d4c5618f5217c6 mismatch
CONFLICT: BLOCK #11524
Nov 29, 2015 8:38:48 AM org.mapdb.StoreWAL close
WARNING: Closing storage with uncommited data, those data will be discarded.
08:38:48.182 ERROR net - Eth handling failed
java.lang.NullPointerException: null
	at org.mapdb.StoreWAL.putDataSingleWithoutLink(StoreWAL.java:383) ~[mapdb-2.0-beta8.jar:na]
	at org.mapdb.StoreDirect.putData(StoreDirect.java:713) ~[mapdb-2.0-beta8.jar:na]
	at org.mapdb.StoreDirect.update2(StoreDirect.java:426) ~[mapdb-2.0-beta8.jar:na]
	at org.mapdb.StoreCached.flushWriteCacheSegment(StoreCached.java:389) ~[mapdb-2.0-beta8.jar:na]
	at org.mapdb.StoreWAL.commit(StoreWAL.java:734) ~[mapdb-2.0-beta8.jar:na]
	at org.mapdb.Engine$CloseOnJVMShutdown.commit(Engine.java:487) ~[mapdb-2.0-beta8.jar:na]
	at org.mapdb.DB.commit(DB.java:2621) ~[mapdb-2.0-beta8.jar:na]
	at org.ethereum.db.BlockQueueImpl.add(BlockQueueImpl.java:140) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.sync.SyncQueue.addNew(SyncQueue.java:215) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.handler.EthHandler.processNewBlock(EthHandler.java:256) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.net.eth.handler.EthHandler.channelRead0(EthHandler.java:135) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
````

**Comment by Nashatyrev** [comment]
Can you please give us more details on why do you suppose this is `getNonce` problem?

**Comment by skydogch** [comment]
Hi @Nashatyrev , 

I have tested two scenarios:

Scenario 1:
I use intellij and I stop the execution in the *getNonce* command with the debugger. In the mean time, the logs concerning the connection with the geth peer appear in the console (everything fine till here). When I execute getNonce, then the *block conflict* message appears in the console.

Scenario 2:
I run the application without breakpoints. Then the *block conflict* appears.

I will test it again but using only one Transaction as you proposed in the [issue 330](https://github.com/ethereum/ethereumj/issues/330) and I will let you know.

**Comment by skydogch** [comment]
Scenario 3:
If I don't use the getNonce, no block conflict is produced. I know that it is weird, but that are the results I am getting.

**Comment by Nashatyrev** [comment]
"cd2a3d9f938e13cd947ec05abc7fe734df8dd826".getBytes() you need to change that to
Hex.decode("cd2a3d9f938e13cd947ec05abc7fe734df8dd826")

The getNonce() calls getAccountStateOrCreateNew() thus creating a new account => conflict.
Though this looks odd, need to think about if we should mutate the repository in such cases
