### ISSUE TITLE
java.lang.NullPointerException at org.ethereum.sync.SyncManager.startMaster(SyncManager.java:360)

### ISSUE THREAD

**Issue by mtgran** [ethereum/ethereumj#334]
Hello,

I am using the stage_2-snapshot and NullPointerException is generated during the start-up of the node:

--

2015-12-21 23:15:40.066  INFO 8444 --- [pool-3-thread-1] sync                                     : Peer 4c7edd98: its chain is better than previously known: 3184875921 vs 16384, rotate master peer
2015-12-21 23:15:40.068 ERROR 8444 --- [pool-3-thread-1] net                                      : Error

java.lang.NullPointerException: null
	at org.spongycastle.util.encoders.Hex.toHexString(Hex.java:19) ~[core-1.51.0.0.jar:na]
	at org.ethereum.sync.SyncManager.startMaster(SyncManager.java:360) ~[ethereumj-core-1.0.0-stage_2-SNAPSHOT.jar:na]
	at org.ethereum.sync.SyncManager.addPeer(SyncManager.java:194) ~[ethereumj-core-1.0.0-stage_2-SNAPSHOT.jar:na]
	at org.ethereum.net.server.ChannelManager.process(ChannelManager.java:78) ~[ethereumj-core-1.0.0-stage_2-SNAPSHOT.jar:na]
	at org.ethereum.net.server.ChannelManager.processNewPeers(ChannelManager.java:60) ~[ethereumj-core-1.0.0-stage_2-SNAPSHOT.jar:na]
	at org.ethereum.net.server.ChannelManager.access$000(ChannelManager.java:26) ~[ethereumj-core-1.0.0-stage_2-SNAPSHOT.jar:na]
	at org.ethereum.net.server.ChannelManager$1.run(ChannelManager.java:44) ~[ethereumj-core-1.0.0-stage_2-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

**Comment by mtgran** [comment]
update:

I've deleted the folders under database.dir to see if this message desapears: "its chain is better than previously known: 401565312 vs 16384"

But the message still appears followed by the NullPointerException -> https://gist.github.com/mtgran/31c4ddfd1a44d052ded7#file-gistfile1-txt-L29-L37

**Comment by mtgran** [comment]
This issue is outdated, it doesn't appear in the new stage version. I close the ticket
