### ISSUE TITLE
Commit afe4d5d - BadJumpDestinationException - Operation with pc isn't 'JUMPDEST': PC[2];

### ISSUE THREAD

**Issue by mtgran** [ethereum/ethereumj#342]
Hi guys,

I've got a **BadJumpDestinationException** several times running my ethereumj node. I don't know what is the root of the issue, it simply appears in the VM log: 

[https://gist.github.com/mtgran/6ac9c019bb351a795631#file-badjumpdestinationexception-L5441-L5462](url)

```
org.ethereum.vm.program.Program$BadJumpDestinationException: Operation with pc isn't 'JUMPDEST': PC[2];
	at org.ethereum.vm.program.Program$Exception.badJumpDestination(Program.java:1137) ~[ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.vm.program.Program.verifyJumpDest(Program.java:1006) ~[ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.vm.VM.step(VM.java:945) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.vm.VM.play(VM.java:1177) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:259) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:720) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:695) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:438) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:326) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.sync.SyncQueue.produceQueue(SyncQueue.java:123) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.sync.SyncQueue.access$000(SyncQueue.java:31) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at org.ethereum.sync.SyncQueue$1.run(SyncQueue.java:104) [ethereumj-core-1.1.0-stage-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
```

**Comment by romanman** [comment]
Hi @mtgran : it's ok from the blockchain perspective , 
the contract is bad compiled so it violates some rule 
of the VM - but that is normal cause we should be dealing 
with user deploy and run badly compiled contracts.

@Nashatyrev : maybe the log should be so aggressive 
for that one...

**Comment by Nashatyrev** [comment]
@romanman We have a bunch of unnecessary aggressive log ERROR messages which need to be cleaned up

**Comment by romanman** [comment]
Yes, that one is a good example.

Roman

**Comment by Nashatyrev** [comment]
This doesn't appear to be ERROR level message. This is INFO level message which is not printed to console by default but good to have in logs in case of unexpected behavior
