### ISSUE TITLE
Contract compile error

### ISSUE THREAD

**Issue by zhouyuanbin** [ethereum/ethereumj#372]
I’ve got the contract error message as below:
```
15:40:28.642 ERROR [RegularNode1]  RegularNode1 Error : 
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3607)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
    at org.ethereum.solidity.compiler.CompilationResult.parse(CompilationResult.java:17)
    at com.paff.bankblock.ContractTest$RegularNode.testContract(ContractTest.java:337)
    at com.paff.bankblock.ContractTest$RegularNode.access$100(ContractTest.java:165)
    at com.paff.bankblock.ContractTest$RegularNode$2.run(ContractTest.java:269)
    at java.lang.Thread.run(Thread.java:745)
```
The contract content:
```
contract BlockStore{
   struct DataItem{
     bytes value;
     uint timestamp;
   }
   mapping(address=>mapping(bytes32=>DataItem)) data;

  function BlockStore(){
  }
  event eventSave(address indexed account,bytes32 key,bytes value);
  function getContractAddress() returns(address){
      return this;
  }
  function setValue(bytes32 key, bytes value){
      data[msg.sender][key].value = value;
      data[msg.sender][key].timestamp = now;
      eventSave(msg.sender,key,value);
  }
  function getValue(address addr, bytes32 key) constant returns(bytes){
      return data[addr][key].value;
  }
}
```
When will the problem be solved? Thank you.

**Comment by Nashatyrev** [comment]
Should work on Mac with the latest revision
