### ISSUE TITLE
Got an error while a Redis node merged a longer chain from other node.

### ISSUE THREAD

**Issue by mhoudg** [ethereum/ethereumj#397]
I had two nodes running with a modified genesis, one of them works with a Redis server, the other one works with the default LevelDB. They work together fine while keep connected to each other.

I had disconnected them from each for a while, both servers mined by themselves. The LevelDB one mined more blocks(about 190), while the Redis one mined less blocks(about 130). 

After that, I connected them up, an error occur like below on the Redis one. The server action looks ok after that, I'm not really sure if it was really no problem:

```
272910 INFO  state - applied reward for block: [134]
  state: [d5e9981b37c55162924ad0c73e34a1097ab959bc82fd6f671efdb12b55340a16]
272910 INFO  general - Flush details in: 0.35 ms, 1 keys, 0.00MB
272911 INFO  general - Flush 'state' in: 0.31 ms, 2 nodes, 0.00MB
272911 INFO  general - RepositoryImpl.flush took 1 ms
272995 INFO  c.e.s.ethereum.EthereumListener - Do something on block: 134
272995 INFO  blockchain - Rebranching: 90b38e ~> 4fcfa4
273012 ERROR blockqueue - Error processing block #134 (4fcfa4 <~ 150405) Txs:0, Unc: 0:
redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'hmset' command
	at redis.clients.jedis.Protocol.processError(Protocol.java:115) ~[jedis-2.6.0.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:133) ~[jedis-2.6.0.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:202) ~[jedis-2.6.0.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:285) ~[jedis-2.6.0.jar:na]
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:184) ~[jedis-2.6.0.jar:na]
	at redis.clients.jedis.BinaryJedis.hmset(BinaryJedis.java:828) ~[jedis-2.6.0.jar:na]
	at org.ethereum.datasource.redis.RedisMap$6.accept(RedisMap.java:107) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.datasource.redis.RedisMap$6.accept(RedisMap.java:100) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.datasource.redis.RedisStorage$4.apply(RedisStorage.java:93) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.datasource.redis.RedisStorage$4.apply(RedisStorage.java:90) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.datasource.redis.RedisStorage.pooledWithResult(RedisStorage.java:103) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.datasource.redis.RedisStorage.pooled(RedisStorage.java:90) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.datasource.redis.RedisMap.putAll(RedisMap.java:100) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.datasource.redis.RedisDataSource.updateBatch(RedisDataSource.java:83) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.db.DetailsDataStore.flushInternal(DetailsDataStore.java:96) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.db.DetailsDataStore.flush(DetailsDataStore.java:73) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.db.RepositoryImpl.flush(RepositoryImpl.java:228) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.core.BlockchainImpl.tryConnectAndFork(BlockchainImpl.java:285) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:348) ~[ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.sync.SyncQueue.produceQueue(SyncQueue.java:123) [ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.sync.SyncQueue.access$100(SyncQueue.java:36) [ethereumj-core-1.2.0-RELEASE.jar:na]
	at org.ethereum.sync.SyncQueue$2.run(SyncQueue.java:102) [ethereumj-core-1.2.0-RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
273013 ERROR blockqueue - Block dump: f90211f9020ca0150405fb9ef035f3ea9e694d44fb8f58e4167a36fc49ecd41d6cd16b7abb4bbea01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479430d2745a0f1bc587717c3681fbc7842555cc6cdea0d5e9981b37c55162924ad0c73e34a1097ab959bc82fd6f671efdb12b55340a16a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008310488081868490000000808457298f25935a4320726573656172636820706f7765726564a0c730c4484d0e3143809f664f231f4e2a5e519c8837eac58fd485af4d6a9e1291884c49fe7cb4f6209ac0c0
273016 INFO  state - applied reward for block: [135]
  state: [d24f7539edb20b1e2662aabaad05c3ac2a421dc45338be44e119af5799b43841]
273018 INFO  general - Flush details in: 0.43 ms, 1 keys, 0.00MB
273018 INFO  general - Flush 'state' in: 0.34 ms, 2 nodes, 0.00MB
273018 INFO  general - RepositoryImpl.flush took 1 ms
273126 INFO  c.e.s.ethereum.EthereumListener - Do something on block: 135
273128 INFO  blockqueue - Success importing BEST: block.number: 135, block.hash: 465dbd, tx.size: 0
```

**Comment by mhoudg** [comment]
There was a block dump info on console:

```
14:26:13.291 ERROR blockqueue - Block dump: f90212f9020da02defade2f39f80bec66a4964b880679b720291d41269580719c7a91d22bb85caa01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479430d2745a0f1bc587717c3681fbc7842555cc6cdea05eb3f4e4da9808b309baff08295918ef3f8fea50563eb7a664e038e09b2c0ac0a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008310e3c482011f849000000080845729960e935a4320726573656172636820706f7765726564a04785756a8b2d882d09888249751f8715b8086133d3862294e00986c5a0fd8c19883c73dba8738db5cac0c0
```

**Comment by romanman** [comment]
Hi @mhoudg , we have tested Reddis and apparently it 
is more cache than a transnational reliable db for state saving
we soon have to remove it classes for core. 

So LevelDb is your best option.

**Comment by Nashatyrev** [comment]
Redis db is no more core part
