### ISSUE TITLE
NullPointerException in 1.2.5

### ISSUE THREAD

**Issue by jlopp** [ethereum/ethereumj#399]
When I upgraded EthereumJ to 1.2.5 I'm seeing a lot of these NPEs, though they don't appear to be fatal:

`05-12 09:44:49.756 [nioEventLoopGroup-128-1] ERROR net - P2p handling failed
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at org.ethereum.net.rlpx.MessageCodec.getCode(MessageCodec.java:206)
	at org.ethereum.net.rlpx.MessageCodec.splitMessageToFrames(MessageCodec.java:168)
	at org.ethereum.net.rlpx.MessageCodec.encode(MessageCodec.java:160)
	at org.ethereum.net.rlpx.MessageCodec.encode(MessageCodec.java:37)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 11 common frames omitted
`

**Comment by romanman** [comment]
@gubatron : we need more info , 
can you upload the full log with 
.net. package on details.

**Comment by gubatron** [comment]
I didn't have this issue myself, I just looked at the backtrace of the issue report.

**Comment by Nashatyrev** [comment]
No such exception was detected on the latest `develop` on ~20 peers running for 1 week. 
Anyway this ERROR should now be a WARN
