### ISSUE TITLE
[general] Uncaught exception

### ISSUE THREAD

**Issue by nickmelis** [ethereum/ethereumj#417]
When running EthereumJ v1.2.7 against morden, I get the following exception in the logs:

`13:40:51.707 ERROR [general]  Uncaught exception
java.util.NoSuchElementException
	at java.util.concurrent.LinkedBlockingQueue$Itr.next(LinkedBlockingQueue.java:826)
	at java.util.Collections.min(Collections.java:635)
	at org.ethereum.net.rlpx.discover.PeerConnectionTester$MutablePriorityQueue.take(PeerConnectionTester.java:129)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by Nashatyrev** [comment]
Thanks for reporting this. The exception should be fixed in `1.2.7-SNAPSHOT`. If you are observing it on this build please reopen
