### ISSUE TITLE
Exception thrown as a result of 'Too many open files'

### ISSUE THREAD

**Issue by Melvillian** [ethereum/ethereumj#453]
When doing a full sync of the mainnet chain, somewhere after block #1500000 I will see either a SocketException or DBException thrown because I had run out of usable file descriptors (Too many files open). Here is a paste of one such error

```
07-22 02:09:45.428 [main] ERROR db - Exception. Retrying again...
org.iq80.leveldb.DBException: IO error: /data/bitgo/database/state/549361.ldb: Too many open files
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:90)
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:77)
        at org.ethereum.datasource.LevelDbDataSource.get(LevelDbDataSource.java:132)
        at org.ethereum.trie.Cache.get(Cache.java:59)
        at org.ethereum.trie.TrieImpl.getNode(TrieImpl.java:377)
        at org.ethereum.trie.TrieImpl.get(TrieImpl.java:193)
        at org.ethereum.trie.TrieImpl.get(TrieImpl.java:207)
        at org.ethereum.trie.TrieImpl.get(TrieImpl.java:207)
        at org.ethereum.trie.TrieImpl.get(TrieImpl.java:207)
        at org.ethereum.trie.TrieImpl.get(TrieImpl.java:207)
        at org.ethereum.trie.TrieImpl.get(TrieImpl.java:127)
        at org.ethereum.trie.SecureTrie.get(SecureTrie.java:20)
        at org.ethereum.db.RepositoryImpl.getAccountState(RepositoryImpl.java:553)
        at org.ethereum.db.RepositoryImpl.isExist(RepositoryImpl.java:577)
        at org.ethereum.db.RepositoryTrack.isExist(RepositoryTrack.java:93)
        at org.ethereum.db.RepositoryTrack.getCode(RepositoryTrack.java:245)
        at org.ethereum.core.TransactionExecutor.call(TransactionExecutor.java:209)
        at org.ethereum.core.TransactionExecutor.execute(TransactionExecutor.java:181)
        at com.bitgo.EthIndexer.MongoTransactionStore.executeTxWithoutCommitment(MongoTransactionStore.java:461)
        at com.bitgo.EthIndexer.Indexer.getTransactionReceiptsForBlock(Indexer.java:495)
        at com.bitgo.EthIndexer.Indexer.indexMissedBlocks(Indexer.java:445)
        at com.bitgo.EthIndexer.BitGoServer.runIndexer(BitGoServer.java:83)
        at com.bitgo.EthIndexer.BitGoServer.<init>(BitGoServer.java:42)
        at com.bitgo.EthIndexer.BitGoServer.main(BitGoServer.java:29)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /data/bitgo/database/state/549361.ldb: Too many open files
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:316)
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:300)
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:293)
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:85)
        ... 23 common frames omitted
```

This occurs even after using `ulimit -n` to set the number of allowable open files to a large number (in our case we set it to 65,000).

From running `lsof | grep java` I can see that most of the open file descriptors are for files in the `details-storage` directory, but as you can see from the error above there are other files under the `database` top-level directory that get opened.

This is a pretty serious error, as it's hard to predict and prevents any further syncing or database connections (which is where the SocketExceptions come from).

**Comment by Nashatyrev** [comment]
I hope that problem should cease after fixing #427
Feel free to reopen if still reproducible on the latest SNAPSHOT

**Comment by Nashatyrev** [comment]
Just got on the latest `develop`: 
```
org.mapdb.DBException$VolumeIOError: IO failed
        at org.mapdb.Volume$RandomAccessFileVol.<init>(Volume.java:2679)
        at org.mapdb.Volume$RandomAccessFileVol$1.makeVolume(Volume.java:2656)
        at org.mapdb.Volume$VolumeFactory.makeVolume(Volume.java:115)
        at org.mapdb.WriteAheadLog.startNextFile(WriteAheadLog.java:118)
        at org.mapdb.WriteAheadLog.ensureFileReady(WriteAheadLog.java:983)
        at org.mapdb.WriteAheadLog.walPutByteArray(WriteAheadLog.java:885)
        at org.mapdb.StoreWAL.putDataSingleWithoutLink(StoreWAL.java:268)
        at org.mapdb.StoreDirect.putData(StoreDirect.java:708)
        at org.mapdb.StoreDirect.update2(StoreDirect.java:420)
        at org.mapdb.StoreCached.flushWriteCacheSegment(StoreCached.java:454)
        at org.mapdb.StoreCached.flushWriteCache(StoreCached.java:429)
        at org.mapdb.StoreWAL.commit(StoreWAL.java:591)
        at org.mapdb.Engine$CloseOnJVMShutdown.commit(Engine.java:487)
        at org.mapdb.DB.commit(DB.java:2647)
        at org.ethereum.net.rlpx.discover.NodeManager.dbWrite(NodeManager.java:180)
        at org.ethereum.net.rlpx.discover.NodeManager.access$100(NodeManager.java:36)
        at org.ethereum.net.rlpx.discover.NodeManager$3.run(NodeManager.java:131)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.FileNotFoundException: database/network/discovery.wal.0 (Too many open files)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
        at org.mapdb.Volume$RandomAccessFileVol.<init>(Volume.java:2667)
        ... 18 common frames omitted
Oct 08, 2016 2:57:48 AM org.mapdb.Volume finalize
WARNING: Open Volume was GCed, possible file handle leak.
04:52:02.007 WARN [discover]  UDP channel closed. Recreating after 5 sec pause...
04:52:07.008 ERROR [discover]  Can't start discover: 
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioDatagramChannel
        at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:455)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:306)
        at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:271)
        at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:267)
        at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:249)
        at org.ethereum.net.rlpx.discover.UDPListener.start(UDPListener.java:119)
        at org.ethereum.net.rlpx.discover.UDPListener$1.run(UDPListener.java:59)
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:87)
        at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:115)
        at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:453)
        ... 6 common frames omitted
Caused by: java.net.SocketException: Too many open files
        at sun.nio.ch.Net.socket0(Native Method)
        at sun.nio.ch.Net.socket(Net.java:441)
        at sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:116)
        at sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:42)
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:85)
```

**Comment by Nashatyrev** [comment]
May be that's MapDB issue (`WARNING: Open Volume was GCed, possible file handle leak.`), but may be it just the result of the exception withing MapDB above.
Another idea to catch this is to run a script constantly querying process opened files

**Comment by Nashatyrev** [comment]
The latter case could be related to the deadlock issue #568 where all the networking stuff is stuck, so we finally got 65K of opened **inbound** TCP connections
