### ISSUE TITLE
NPE after initialization 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#493]
Doesn't affect the functionality. Might be related to issue #492 

18:33:35.796 INFO [sync] Initializing SyncManager.
java.lang.NullPointerException
at org.ethereum.sync.SyncPool.logActivePeers(SyncPool.java:147)
at org.ethereum.sync.SyncManager$5.run(SyncManager.java:444)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by zilm13** [comment]
From my research, null peer cannot be added to activePeers in SyncPool. So the only cause of the issue - null channelManager. We cannot guarantee that autowiring is complete when it's done by setters added in reflection, the only way to guarantee it is to move @Autowired to constructor. Other option is to check it in every method, but it's really bad approach.

**Comment by zilm13** [comment]
Please, take a look #520 . It should eliminate this issue.

**Comment by Nashatyrev** [comment]
Resolved with #492
