### ISSUE TITLE
java.lang.NumberFormatException: Zero length BigInteger when performing callConstantFunction on contract

### ISSUE THREAD

**Issue by martintreurnicht** [ethereum/ethereumj#510]
I'm running a private chain based of https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/samples/PrivateMinerSample.java
Since `1.3.0-RELEASE` i'm getting the following error:

```
java.lang.NumberFormatException: Zero length BigInteger
	at java.math.BigInteger.<init>(BigInteger.java:302) ~[na:1.8.0_102]
	at org.ethereum.vm.program.invoke.ProgramInvokeFactoryImpl.createProgramInvoke(ProgramInvokeFactoryImpl.java:96) ~[ethereumj-core-1.3.0-RELEASE.jar:na]
	at org.ethereum.core.TransactionExecutor.call(TransactionExecutor.java:213) ~[ethereumj-core-1.3.0-RELEASE.jar:na]
	at org.ethereum.core.TransactionExecutor.execute(TransactionExecutor.java:179) ~[ethereumj-core-1.3.0-RELEASE.jar:na]
	at org.ethereum.facade.EthereumImpl.callConstantImpl(EthereumImpl.java:263) ~[ethereumj-core-1.3.0-RELEASE.jar:na]
	at org.ethereum.facade.EthereumImpl.callConstantFunction(EthereumImpl.java:287) ~[ethereumj-core-1.3.0-RELEASE.jar:na]
	at org.ethereum.facade.EthereumImpl.callConstantFunction(EthereumImpl.java:276) ~[ethereumj-core-1.3.0-RELEASE.jar:na]
```

Further investigation shows that when performing `ethereum.repository.getBalance()` for the contract address returns a ByteArray with a single value of 1, ie `[ 1 ]`.

Further more, this only seems to happen when connecting to a miner node, and this only happens on `1.3.0-RELEASE`. I reverted back to `1.3.0-RC7`, and everything is working again.

**Comment by fmurialdo** [comment]
This has been fixed in commit `bd60cc1ea8f456c84f37f29710ff2390d6b93441` on Sept 9th

What leads to this error in 1.3.0-RELEASE is the following: 

EthereumImpl.java:310
  `Transaction tx = CallTransaction.createCallTransaction(0, 0, 100000000000000L,
               receiveAddress, 0, function, funcArgs);`

The second argument is the gasPrice

`longToBytesNoLeadZeroes(gasPrice)` converts 0 into empty array

So gasPrice is stored in the transaction as byte[0]

Then the code in callConstantFunction does 

`byte[] gasPrice = tx.getGasPrice();`

and therefore it is failing on

`new BigInteger(gasPrice).longValue()`

**Comment by Nashatyrev** [comment]
@martintreurnicht I believe it is not reproducible with `VM = ERROR` log level?
We will include the fix @fmurialdo mentioned to the next hotfix release (`1.3.1`)

**Comment by martintreurnicht** [comment]
@Nashatyrev I'm looking at this now. I believe the `develop` should solve my problem. I will test and confirm

**Comment by martintreurnicht** [comment]
@Nashatyrev i can confirm that this is working on `develop`, looking forward to `1.3.1` release 👍
