### ISSUE TITLE
State Trie is broken most likely due to some concurrency issue

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#517]
Other peers imported this block fine. Probably some thread racing between SyncThread and PendingTransactions processing 
```
07:12:51.771 ERROR [sync] Error processing block #2244382 (d6a0d1 <~ 00badf) Txs:1, Unc: 0:                                                                                                               
java.lang.RuntimeException: Invalid Trie state, missing node b055c63716e50987ffa52af7f4e5a1242f85ae541d82e3c189310a64e6b19a5d                                                                             
        at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:253) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                                    
        at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:306) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                                    
        at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:306) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                                    
        at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:306) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                                    
        at org.ethereum.trie.TrieImpl.insertOrDelete(TrieImpl.java:229) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                            
        at org.ethereum.trie.TrieImpl.update(TrieImpl.java:161) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                                    
        at org.ethereum.trie.SecureTrie.update(SecureTrie.java:25) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                                 
        at org.ethereum.db.RepositoryImpl.updateAccountState(RepositoryImpl.java:512) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                              
        at org.ethereum.db.RepositoryImpl.updateBatch(RepositoryImpl.java:190) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                     
        at org.ethereum.db.RepositoryTrack.commit(RepositoryTrack.java:350) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                        
        at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:838) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                    
        at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:805) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                  
        at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:523) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                           
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:405) ~[ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                  
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:249) [ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                         
        at org.ethereum.sync.SyncManager.access$200(SyncManager.java:35) [ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                            
        at org.ethereum.sync.SyncManager$4$1.run(SyncManager.java:130) [ethereumj-core-1.3.0-RELEASE.jar:na]                                                                                              
```

**Comment by Nashatyrev** [comment]
[ethereum-2016-09-12_07.0.zip](https://github.com/ethereum/ethereumj/files/470524/ethereum-2016-09-12_07.0.zip)

**Comment by zilm13** [comment]
I'm getting same error with latest develop both on MainNet and Morden.
And not getting it when running `feature/refactor-init-sequence` with same DB.
