### ISSUE TITLE
ContractDetails trie is broken when accessing concurrently 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#521]
```
java.lang.RuntimeException: Invalid Trie state, missing node 9c448d0e49d05ed4280a69705c31c73b1cb8e8e5eec5926761027e7acb0e3043
	at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:265)
	at org.ethereum.trie.TrieImpl.insertOrDelete(TrieImpl.java:241)
	at org.ethereum.trie.TrieImpl.update(TrieImpl.java:166)
	at org.ethereum.trie.SecureTrie.update(SecureTrie.java:25)
	at org.ethereum.db.ContractDetailsImpl.put(ContractDetailsImpl.java:78)
	at org.ethereum.db.RepositoryImpl.addStorageRow(RepositoryImpl.java:451)
	at org.ethereum.db.RepositoryTest$2.run(RepositoryTest.java:987)
	at java.lang.Thread.run(Thread.java:745)
```

Reproducible with `org.ethereum.db.RepositoryTest#testMultiThread`

Similar to issue #517 but has very different origin

**Comment by Nashatyrev** [comment]
Resolved with commit https://github.com/ethereum/ethereumj/commit/9d0ea48c7fa5ace60e7b98fdb4d718535b23c01f
