### ISSUE TITLE
Deadlock in networking 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#568]
```
Found one Java-level deadlock:
=============================
"pool-10-thread-1":
  waiting to lock monitor 0x00007fee2000f1c8 (object 0x000000077be89680, a org.ethereum.net.eth.handler.Eth62),
  which is held by "nioEventLoopGroup-3-3"
"nioEventLoopGroup-3-3":
  waiting to lock monitor 0x00007fedd8013448 (object 0x00000007068224c8, a java.util.Collections$SynchronizedMap),
  which is held by "pool-10-thread-1"

Java stack information for the threads listed above:
===================================================
"pool-10-thread-1":
        at org.ethereum.net.eth.handler.Eth62.sendTransaction(Eth62.java:168)
        - waiting to lock <0x000000077be89680> (a org.ethereum.net.eth.handler.Eth62)
        at org.ethereum.net.server.Channel.sendTransaction(Channel.java:350)
        at org.ethereum.net.server.ChannelManager.sendTransaction(ChannelManager.java:235)
        - locked <0x00000007068224c8> (a java.util.Collections$SynchronizedMap)
        at org.ethereum.net.submit.TransactionTask.call(TransactionTask.java:47)
        at org.ethereum.net.submit.TransactionTask.call(TransactionTask.java:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
"nioEventLoopGroup-3-3":
        at java.util.Collections$SynchronizedMap.values(Collections.java:2075)
        - waiting to lock <0x00000007068224c8> (a java.util.Collections$SynchronizedMap)
        at org.ethereum.net.server.ChannelManager.notifyDisconnect(ChannelManager.java:338)
        at org.ethereum.net.server.EthereumChannelInitializer$1.operationComplete(EthereumChannelInitializer.java:67)
        at org.ethereum.net.server.EthereumChannelInitializer$1.operationComplete(EthereumChannelInitializer.java:63)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:406)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:956)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:608)
      at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:956)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:608)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:586)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1107)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:543)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:528)
        at io.netty.channel.ChannelDuplexHandler.close(ChannelDuplexHandler.java:73)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:543)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:528)
        at io.netty.channel.ChannelDuplexHandler.close(ChannelDuplexHandler.java:73)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:543)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:528)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:394)
        at org.ethereum.net.MessageQueue.disconnect(MessageQueue.java:106)
        at org.ethereum.net.MessageQueue.disconnect(MessageQueue.java:101)
        at org.ethereum.net.eth.handler.EthHandler.disconnect(EthHandler.java:107)
        at org.ethereum.net.eth.handler.Eth62.dropConnection(Eth62.java:778)
        - locked <0x000000077be89680> (a org.ethereum.net.eth.handler.Eth62)
        at org.ethereum.net.eth.handler.Eth62.processBlockHeaders(Eth62.java:361)
        - locked <0x000000077be89680> (a org.ethereum.net.eth.handler.Eth62)
        at org.ethereum.net.eth.handler.Eth62.channelRead0(Eth62.java:122)
        at org.ethereum.net.eth.handler.Eth62.channelRead0(Eth62.java:46)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at org.ethereum.net.rlpx.NettyByteToMessageCodec.channelRead(NettyByteToMessageCodec.java:56)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Nashatyrev** [comment]
The full dump:
[thread.dump.txt](https://github.com/ethereum/ethereumj/files/522811/thread.dump.txt)
