### ISSUE TITLE
Fails to start when using genesis with empty alloc and miner activated

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#596]
Genesis:
```
{
  "alloc": {  },
  "nonce": "0x0000000000000042",
  "difficulty": "0x000002",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  "gasLimit": "0x4c4b40"
}
```

Stacktrace:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMiner': Invocation of init method failed; nested exception is java.lang.RuntimeException: Invalid Trie state, missing node 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreatbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 53 common frames omitted
Caused by: java.lang.RuntimeException: Invalid Trie state, missing node 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:265)
	at org.ethereum.trie.TrieImpl.insertOrDelete(TrieImpl.java:241)
	at org.ethereum.trie.TrieImpl.update(TrieImpl.java:166)
	at org.ethereum.trie.SecureTrie.update(SecureTrie.java:25)
	at org.ethereum.db.RepositoryImpl.updateAccountState(RepositoryImpl.java:512)
	at org.ethereum.db.RepositoryImpl.updateBatch(RepositoryImpl.java:190)
	at org.ethereum.db.RepositoryTrack.commit(RepositoryTrack.java:350)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:861)
	at org.ethereum.core.BlockchainImpl.createNewBlock(BlockchainImpl.java:476)
	at org.ethereum.mine.BlockMiner.restartMining(BlockMiner.java:218)
	at org.ethereum.mine.BlockMiner.stng(BlockMiner.java:115)
	at org.ethereum.mine.BlockMiner.init(BlockMiner.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 65 common frames omitted
```

**Comment by zilm13** [comment]
This bug is not actual for develop
