### ISSUE TITLE
NullPointerException at SyncManager when starting on an empty Db (ether.camp testnet)

### ISSUE THREAD

**Issue by adridadou** [ethereum/ethereumj#624]
When I start syncing ether.camp testnet network on an empty db, I get a null pointer exception:
````
java.lang.NullPointerException
	at org.ethereum.sync.SyncPool.logActivePeers(SyncPool.java:152)
	at org.ethereum.sync.SyncManager$5.run(SyncManager.java:444)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

This happens on the released version 1.3.9

**Comment by adridadou** [comment]
also it doesn't sync because it can't connect to any of the three peers

**Comment by zilm13** [comment]
@adridadou do you have `sync.enabled = true` or you start it manually?

**Comment by adridadou** [comment]
Here is my config:
peer.discovery = {
enabled = false
}
peer.active = [{ url = "enode://9bcff30ea776ebd28a9424d0ac7aa500d372f918445788f45a807d83186bd52c4c0afaf504d77e2077e5a99f1f264f75f8738646c1ac3673ccc652b65565c3bb@peer-1.ether.camp:30303"},{ url = "enode://c2b35ed63f5d79c7f160d05c54dd60b3ba32d455dbb10a5fe6fde44854073db02f9a538423a63a480126c74c7f650d77066ae446258e3d00388401d419b99f88@peer-2.ether.camp:30303"},{ url = "enode://8246787f8d57662b850b354f0b526251eafee1f077fc709460dc8788fa640a597e49ffc727580f3ebbbc5eacb34436a66ea40415fab9d73563481666090a6cf0@peer-3.ether.camp:30303"}]
peer.listen.port = 0
peer.networkId = -95
peer.p2p.eip8 = false
genesis = frontier-test.json
blockchain.config.name = "testnet"
sync.enabled = true
database = {
dir = ethercamp-test
}

So yes I have sync.enabled = true 

I see in the logs that it tries to connect to the peers but never succeeds apparently

**Comment by zilm13** [comment]
`peer.networkId = -95` should be 161
Tried it on 1.3.9 - everything works fine

**Comment by adridadou** [comment]
Good catch thank you!
I'll have a look. I think I know where the problem comes from

**Comment by adridadou** [comment]
The sync works but I still have the NullPointerException when I start the node
