### ISSUE TITLE
FastSync state trie error on Ropsten

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#635]
For pivot block #166785
`0x96b3bc38ff2a7d0bbd12c25f3af1f1b863b205d162933b93ebf57476e8604c0b`
```
22:08:21.993 ERROR [sync]  Error processing block #166789 (d2f63f <~ a2fdaf) Txs:8, Unc: 1: 
java.lang.RuntimeException: Invalid Trie state, missing node 6a7f3880effc340b7e4593166c350be1e4f72f43a709f7f24f1fe628d29059a3
	at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:199)
	at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:262)
	at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:262)
	at org.ethereum.trie.TrieImpl.insertOrDelete(TrieImpl.java:175)
	at org.ethereum.trie.TrieImpl.put(TrieImpl.java:100)
	at org.ethereum.trie.SecureTrie.put(SecureTrie.java:30)
	at org.ethereum.trie.SecureTrie.put(SecureTrie.java:9)
	at org.ethereum.datasource.SourceCodec.put(SourceCodec.java:31)
	at org.ethereum.datasource.WriteCache.flushImpl(WriteCache.java:185)
	at org.ethereum.datasource.AbstractChainedSource.flush(AbstractChainedSource.java:47)
	at org.ethereum.datasource.SourceChainBox.flushImpl(SourceChainBox.java:53)
	at org.ethereum.datasource.AbstractChainedSource.flush(AbstractChainedSource.java:47)
	at org.ethereum.datasource.MultiCache.flushChild(MultiCache.java:62)
	at org.ethereum.db.RepositoryRoot$MultiStorageCache.flushChild(RepositoryRoot.java:44)
	at org.ethereum.db.RepositoryRoot$MultiStorageCache.flushChild(RepositoryRoot.java:31)
	at org.ethereum.datasource.MultiCache.flushImpl(MultiCache.java:48)
	at org.ethereum.datasource.AbstractChainedSource.flush(AbstractChainedSource.java:47)
	at org.ethereum.db.RepositoryRoot.getRoot(RepositoryRoot.java:110)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:848)
	at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:813)
	at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:540)
	at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:419)
	at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:168)
	at org.ethereum.sync.SyncManager.access$200(SyncManager.java:34)
	at org.ethereum.sync.SyncManager$4.run(SyncManager.java:125)
	at java.lang.Thread.run(Thread.java:745)
22:08:21.994 ERROR [sync]  Block dump: f90a8bf90216a0a2fdaf6d97fb50f89dd7b60fa7f5934047e864796b013c3f7489eba6256964c6a06837c0332df36acbd41a89775f1a74b85e8a9e9d3cbfc611b533bc712fa9e81594d490af05bf82ef6c6ba034b22d18c39b5d52cc54a0f97366a7632b54c17784a41cba2b967ea6f11352c76144e97603d42b12aeff56a09469900eafa426ee5f4ad109f5048ed6b2475c595c5dd7cd23fb4440642c25d8a0e3f310588a5274bba07f5d224fc9a77cd8ce0612045c76d97e116c23b69a87abb9010004002004004000010000100000000000800508000000000000000000000000000000000000000000000000000000000000004008000000000000100000200000022000000000000000000808000400000000000000004000000000000000010000000000020c000000000880000008004000000000000200000000100000000000000088000010000010000000000000000000002010000080000000000000800200050000000200000007000000000000000000000080000040000004000000400000020000102000000000a000000000400000000000000000000000002000031040000000000000000000000000000a000000008000000000000000000000840c594bd183028b858347e7c48307a568845853f4ff98d783010505846765746887676f312e372e33856c696e7578a01f66de76d67a4a8f208fc56c7bece5bf6655464e3d3150cef40b488783d2e9658819d96f7e4fc654b8f90654f8ac8212028504a817c800830e57e094bb5edd547f7d5dfbbfb26e429b46f3960e9a725780b844095ea7b300000000000000000000000018371e6b3a627c8bb3571c9ed3d03786bb60a91e00000000000000000000000000000000000000000000000000000000000f3e5829a00fb21e9e2436b275a53a313360f848f7338903053c65e88bd3164d87428cf12aa0513fa5ad98514fbd54f0391af61b14453f28a5b422f428fafa1905b22b8598dff8ec8212038504a817c800830e57e09418371e6b3a627c8bb3571c9ed3d03786bb60a91e80b884f09ea2a600000000000000000000000000000000000000000000000000000000000f3e58000000000000000000000000bb5edd547f7d5dfbbfb26e429b46f3960e9a72570000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000cb99947acb2a30db029436434c4d9df5e73c5e7e2aa06c39581c7e8d832de7188811f49b0be6e0ad2b60cbe3882e8e3b3c16babc9686a031f0fb33d1c5d29a108844bf6835f8d30ed07149963203aee181f70f54ca9b5ff8ac8212048504a817c800830e57e094bb5edd547f7d5dfbbfb26e429b46f3960e9a725780b844095ea7b300000000000000000000000018371e6b3a627c8bb3571c9ed3d03786bb60a91e00000000000000000000000000000000000000000000000000000000000db81c2aa0d77c3a60c5c3e93c2d2e7ecb795d140df3bd756bc0edf3ea01e9c2541df1ea47a01b2d829ab109f89868e20e45e3ffc5bbb112633b86bb385dccf741c2d8fc1e04f901ad8212058504a817c800830e57e09426be475dfbc89f87d3e76e6f47b23e13d269d8c980b90144d441987d000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000003000000000000000000000000bb5edd547f7d5dfbbfb26e429b46f3960e9a72570000000000000000000000004958919a8d8ce57aadc346a8880cc707cca7784e000000000000000000000000d805b8fd64787055a9c5bb8c6dc5bbb67199ae830000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000e9104f2029000000000000000000000000000000000000000000000000000000004c1f9908000000000000000000000000000000000000000000000000000000004f27ff0029a0898b5ac6ce7ecd839580f64d52991acbaab408bd3d9afa8e89c1320842c78034a02976f906d103711774fd428c870260dccd739938d6370277d02495a91bd0c491f86f82c9828504a817c8008304cb269432cd3282d33ff58b4ae8402a226a0b27441b7f1a880de0b6b3a7640000801ba0336c72188c9d9808c0febf8df8d1da5172179a93f0f23560631cc746483e5f21a0373e8d53d6548272c128952ca9bd0a2e4b82e16c8adbda8a5a0747141510e1faf8ac820a978504a817c800830e57e094870283380c7da544d2b16d3434709874e3ed77cb80b84446df2ccb000000000000000000000000000000000000000000000000000000005853f4e8000000000000000000000000000000000000000000000000000000000000004e2aa093c5aa3c610adda3cd258d967f1fc81e11c7863dd66e20325d2b4a02fbec2d33a06acb890e50bc5e730443cca9b4feab476ffb6143f511132f7aa38778313c4851f8ac820a988504a817c800830e57e094870283380c7da544d2b16d3434709874e3ed77cb80b84446df2ccb000000000000000000000000000000000000000000000000000000005853f4f8000000000000000000000000000000000000000000000000000000000000004e29a05af63f8f5c5851c80da28f4f8fe9f72a5aca1f6d9a2dbd0196296703dbafe14da0704ba5e8e33f13470356d0b62ef504d4e82c6f96000287261d3066d874f2e440f88b825d9e8504a817c8008303d09094c47aa6c1987ec4737b40a327620c31fd1995602f80a451a34eb80000000000000000000000000000000000000000000000006ccb9affd804a00029a0dce549c78e04b9c5b9b5e986dab41fd9f12582315deddd68b4326d8397ed4c7aa01506a1a7ca7ff7d100bfa41e4e34f4913445fa96b86a7e329d6fd3309d7b4769f90218f90215a0a92286eaed2677a0a78e4ee5796d6b1e3711d824abab42c1b33f04a4e41445e3a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794d490af05bf82ef6c6ba034b22d18c39b5d52cc54a08befab3d3a7cc530d661923189342dc838f34a4e683135b97afd90d6c2b36a28a0928dabda1affd1f2f70bab3710258b009682e73530475fa471690eabf59247f1a0be0662827d5bf277ba4a95f2f06be85da2134be326e0aa7040350bedc3f9a913b9010000000000000000000000100000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000080000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000840c5c62e983028b848347e7c4825c32845853f4df98d783010505846765746887676f312e372e33856c696e7578a040b19de37454744c81fffd885dcb1b421124f9b2a3d1fc8809642201f4cd04a4884ce4736461a4ea02
22:08:21.994 ERROR [sync]  No parent on the chain for block.number: 166790 block.hash: d884fe
22:08:21.994 ERROR [sync]  No parent on the chain for block.number: 166791 block.hash: 60ff5e
22:08:21.994 ERROR [sync]  No parent on the chain for block.number: 166792 block.hash: 22645b
```

**Comment by Nashatyrev** [comment]
Recently fixed a bug which could lead to this issue with high probability: https://github.com/ethereum/ethereumj/commit/ca5c789cce0e9fc9a2d4ce0aa84972764bc4bcbf
Couldn't reproduce this issue with the same pivot block on the latest `develop`

**Comment by zilm13** [comment]
@Nashatyrev I've passed it successfully with merge from the latest develop.
Closing issue.
