### ISSUE TITLE
:ethereumj-core:coveralls start failing with SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#668]
At some point build was broken with the following error:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ethereumj-core:coveralls'.

    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)

    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)

    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)

[..]

Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
```

**Comment by Nashatyrev** [comment]
Related issue: https://github.com/trautonen/coveralls-maven-plugin/issues/16
