### ISSUE TITLE
FastSync NPE error

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#671]
```
19:46:46.987 ERROR [sync]  Fatal FastSync loop error                                                                                                                                                         
java.lang.NullPointerException: null                                                                                                                                                                        at org.ethereum.util.FastByteComparisons.equal(FastByteComparisons.java:32)                                                          at org.ethereum.sync.FastSyncManager.syncSecure(FastSyncManager.java:518)                                                          at org.ethereum.sync.FastSyncManager.main(FastSyncManager.java:599)                                                                   at org.ethereum.sync.FastSyncManager$2.run(FastSyncManager.java:155)                                                                                                                                 
```
This seems to happen because of `BlockDownloader` calls `finishDownload()` before the last headers are pushed. Need some synchronization here

**Comment by Nashatyrev** [comment]
Or (most likely) we received the last chunk with last #0 header (while awaiting for #1)
