### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space after "Generating Full Dataset" 

### ISSUE THREAD

**Issue by dsapaev** [ethereum/ethereumj#710]
I'm try to start gradlew run -PmainClass=org.ethereum.samples.PrivateMinerSample
There is my log:
09:58:10.132 INFO [sampleMiner]  Generating Full Dataset (may take up to 10 min
if not cached)...
09:58:10.236 ERROR [general]  Uncaught exception
java.lang.OutOfMemoryError: Java heap space
        at java.lang.reflect.Array.newInstance(Array.java:75)
        at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1671)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at org.ethereum.mine.Ethash.getFullDataset(Ethash.java:118)
        at org.ethereum.samples.PrivateMinerSample$MinerNode.run(PrivateMinerSam
ple.java:88)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dsapaev** [comment]
You should edit build.gradle to fix it 
ethereum-core/build.gradle


applicationDefaultJvmArgs = ["-server", "-Xss2m", "-Xmx1024M", "-XX:-OmitStackTraceInFastThrow"]
change to
applicationDefaultJvmArgs = ["-server", "-Xss2m", "-Xmx2048M", "-XX:-OmitStackTraceInFastThrow"]

**Comment by cupuyc** [comment]
@Nashatyrev let's try to store DAG data off heap. I think then we could keep our core heap in 500M or 1G bounds.

**Comment by Nashatyrev** [comment]
@cupuyc Hm, good idea! Need to check the performance then

**Comment by Nashatyrev** [comment]
Oh, when using direct ByteBuffer the mine hashrate drops ~2x :(

**Comment by Nashatyrev** [comment]
Offheap DAG showed comparable performance with `Unsafe` access only. Using unsafe `Unsafe` instead of just increasing `-Xmx` doesn't make sense 
Add -Xmx check in the `PrivateMinerSample`: https://github.com/ethereum/ethereumj/commit/ef7652911345c1cd8c27108312b432aabad2612a
