### ISSUE TITLE
ClassCastException occasionally 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#725]
version `1.4.1`
```
java.lang.ClassCastException: org.ethereum.net.eth.handler.Eth62 cannot be cast to org.ethereum.net.eth.handler.Eth63
        at org.ethereum.sync.FastSyncManager.requestNextNodes(FastSyncManager.java:340)
        at org.ethereum.sync.FastSyncManager.retrieveLoop(FastSyncManager.java:413)
        at org.ethereum.sync.FastSyncManager.syncUnsecure(FastSyncManager.java:475)
        at org.ethereum.sync.FastSyncManager.main(FastSyncManager.java:597)
        at org.ethereum.sync.FastSyncManager$2.run(FastSyncManager.java:156)
```

**Comment by arass** [comment]
Loaded 1.4.1 over 1.4.0. Set for Fast Sync. Ropsten.
Wiped DB.
Started process. Got that error message. (and many sync errors followed).

Stopped. Wiped DB folder again. Started. Went ok this time.

**Comment by Nashatyrev** [comment]
@arass that `ClassCastException` shouldn't normally affect overall functionality. But 'and many sync errors followed' looks like a real issue. If you are able to reproduce please share full logs

**Comment by Nashatyrev** [comment]
Should be fixed with merged PR
