### ISSUE TITLE
AppContext initialization failure when running from shadowJar (built on Linux)

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#726]
When `./gradlew shadowJar` on Linux running node via `java -cp ethereumj-core-1.5.0-SNAPSHOT-all.jar org.ethereum.Start` causes various bean init errors (on both Linux and Windows). 

With the jar build on my Linux box I've got: 
```
14:06:05.885 ERROR [general]  Uncaught exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'netStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.ethereum.manager.WorldManager org.ethereum.net.swarm.NetStore.worldManager; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'worldManager' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/manager/WorldManager.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [org.ethereum.core.Repository]: : Error creating bean with name 'repositoryTrack' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/db/RepositoryTrack.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.db.RepositoryTrack]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>(); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryTrack' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/db/RepositoryTrack.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.db.RepositoryTrack]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>()
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:46)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:27)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:23)
	at org.ethereum.Start.main(Start.java:25)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.ethereum.manager.WorldManager org.ethereum.net.swarm.NetStore.worldManager; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'worldManager' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/manager/WorldManager.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [org.ethereum.core.Repository]: : Error creating bean with name 'repositoryTrack' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/db/RepositoryTrack.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.db.RepositoryTrack]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>(); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryTrack' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/db/RepositoryTrack.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.db.RepositoryTrack]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>()
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 15 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'worldManager' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/manager/WorldManager.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [org.ethereum.core.Repository]: : Error creating bean with name 'repositoryTrack' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/db/RepositoryTrack.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.db.RepositoryTrack]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>(); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryTrack' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/db/RepositoryTrack.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.db.RepositoryTrack]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>()
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 17 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryTrack' defined in URL [jar:file:/D:/ws/work/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/db/RepositoryTrack.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.db.RepositoryTrack]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 30 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ethereum.db.RepositoryTrack]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	... 40 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.ethereum.db.RepositoryTrack.<init>()
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getDeclaredConstructor(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	... 41 common frames omitted
```

**Comment by Nashatyrev** [comment]
There is also the following exception has been reported: 
```
22:14:56.168 ERROR [general] Uncaught exception
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pendingStateImpl' defined in URL [jar:file:/home/jamie/Dropbox/etherworkspace/ethereumj/ethereumj-core/build/libs/ethereumj-core-1.5.0-SNAPSHOT-all.jar!/org/ethereum/core/PendingStateImpl.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [org.ethereum.core.BlockchainImpl]: : Error creating bean with name 'blockchainImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.ethereum.core.PendingState org.ethereum.core.BlockchainImpl.pendingState; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'pendingStateImpl': Requested bean is currently in creation: Is there an unresolvable circular reference?; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockchainImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.ethereum.core.PendingState org.ethereum.core.BlockchainImpl.pendingState; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'pendingStateImpl': Requested bean is currently in creation: Is there an unresolvable circular reference?
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
at org.springframework.beans.factory.support.DefaultSingletonBeanRe
```

**Comment by Nashatyrev** [comment]
The problem was solved on my side with `./gradlew clean`
When classes are left from the previous build they are still scanned by the Spring and this leads to initialization mess. 
Closing the issue, please feel free to reopen if still reproducible with 
`./gradlew clean shadowJar`
