### ISSUE TITLE
Issue when generating RLP of Transaction

### ISSUE THREAD

**Issue by Glamdring** [ethereum/ethereumj#911]
I tried to generate the raw representation of a transaction in order to send it via etherscan.io/pushTx, but etherscan reported an error "Invalid signature".

Then I tried to create a transaction and verify it locally, and ethereumj failed parsing its own output:

```
private byte[] sendTx(byte[] senderPrivateKey, byte[] receiveAddress, byte[] data, Ethereum senderNode) throws InterruptedException {
        byte[] fromAddress = ECKey.fromPrivate(senderPrivateKey).getAddress();
        
        BigInteger nonce = senderNode.getRepository().getNonce(fromAddress);
        Integer chainId = senderNode.getChainIdForNextBlock();
        
        Transaction tx = new Transaction(
                ByteUtil.bigIntegerToBytes(nonce),
                ByteUtil.longToBytesNoLeadZeroes(senderNode.getGasPrice()),
                ByteUtil.longToBytesNoLeadZeroes(200000),
                receiveAddress,
                ByteUtil.bigIntegerToBytes(BigInteger.valueOf(1)),  // 1 gwei
                data,
                chainId);

        tx.sign(ECKey.fromPrivate(senderPrivateKey));
        logger.info("Raw transaction: 0x{}", Hex.encodeHexString(tx.getEncodedRaw()));
        
        new Transaction(tx.getEncodedRaw()).verify(); // <-- this throws an exception
        
        senderNode.submitTransaction(tx);
        logger.info("<=== Sending transaction: " + tx);

        return tx.getHash();
    }
```

And the exception is:

```
java.lang.RuntimeException: Error on parsing RLP
	at org.ethereum.core.Transaction.rlpParse(Transaction.java:223)
	at org.ethereum.core.Transaction.verify(Transaction.java:186)
	at com.mypackage.ethereumsync.EthereumService.sendTxAndWait(EthereumService.java:138)
	at com.mypackage.ethereumsync.EthereumService.storeHashInEthereum(EthereumService.java:112)
	at com.mypackage.ethereumsync.EthereumServiceTest.testTransfer(EthereumServiceTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException: null
	at java.math.BigInteger.stripLeadingZeroBytes(BigInteger.java:3995)
	at java.math.BigInteger.<init>(BigInteger.java:346)
	at org.ethereum.crypto.ECKey$ECDSASignature.fromComponents(ECKey.java:599)
	at org.ethereum.crypto.ECKey$ECDSASignature.fromComponents(ECKey.java:610)
	at org.ethereum.core.Transaction.rlpParse(Transaction.java:216)
	... 35 common frames omitted
```

Note (probably irrelevant, but anyway: I've turned off syncing, so that's an unsynced instance)

**Comment by Glamdring** [comment]
What I noticed is that the getEncodedRaw does not include the signature. Maybe that's the issue?

**Comment by Glamdring** [comment]
Okay, confirmed - I created an external getEncodedRaw method that includes the signature and it works.

**Comment by Glamdring** [comment]
On a second look that might be a feature, as getEncodedRaw and getEncoded seem to return pre- and post-signing representations, but the naming is not straightforward and they lack javadoc, which I think they should have

**Comment by adonley** [comment]
I just went through some of the same process. Can we close this issue now?

**Comment by Glamdring** [comment]
@adonley I'd propose adding javadoc to getEncoded() and improving the one on getEncodedRaw(). Otherwise, yes
