### ISSUE TITLE
Too many open files - Can't Sync - Constant Crashing

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/ethereumj#942]
I'm running 1.6.1-RELEASE and my node is constantly crashing. Can't run it for more than say 15-30 minutes before it crashes. It will start syncing blocks then crash and the logs are just full of "Too many open file" error messages.

I'm on Ubuntu Server 16.04.03 x64

```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

```
15:04:28.255 ERROR [sync]  Error processing block #4401693 (e5bdf5 <~ 2bef5b) Txs:58, Unc: 0: 
org.iq80.leveldb.DBException: IO error: /ethereum-harmony/database/blockchain/550456.ldb: Too many open files
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:90)
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:77)
        at org.ethereum.datasource.leveldb.LevelDbDataSource.get(LevelDbDataSource.java:181)
        at org.ethereum.datasource.leveldb.LevelDbDataSource.get(LevelDbDataSource.java:46)
        at org.ethereum.datasource.BatchSourceWriter.get(BatchSourceWriter.java:53)
        at org.ethereum.datasource.WriteCache.get(WriteCache.java:205)
        at org.ethereum.datasource.XorDataSource.get(XorDataSource.java:47)
        at org.ethereum.datasource.XorDataSource.get(XorDataSource.java:30)
        at org.ethereum.datasource.WriteCache.get(WriteCache.java:205)
        at org.ethereum.datasource.WriteCache.get(WriteCache.java:205)
        at org.ethereum.datasource.AsyncWriteCache.get(AsyncWriteCache.java:91)
        at org.ethereum.datasource.SourceCodec.get(SourceCodec.java:53)
        at org.ethereum.datasource.ReadCache.get(ReadCache.java:110)
        at org.ethereum.datasource.SourceChainBox.get(SourceChainBox.java:58)
        at org.ethereum.db.IndexedBlockStore.isBlockExist(IndexedBlockStore.java:196)
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:439)
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:267)
        at org.ethereum.sync.SyncManager.access$600(SyncManager.java:56)
        at org.ethereum.sync.SyncManager$5.run(SyncManager.java:177)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /ethereum-harmony/database/blockchain/550456.ldb: Too many open files
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:316)
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:300)
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:293)
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:85)
        ... 19 common frames omitted
15:04:28.265 ERROR [sync]  Error processing block #4401694 (08b860 <~ e5bdf5) Txs:44, Unc: 0: 
org.iq80.leveldb.DBException: IO error: /ethereum-harmony/database/blockchain/551812.ldb: Too many open files
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:90)
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:77)
        at org.ethereum.datasource.leveldb.LevelDbDataSource.get(LevelDbDataSource.java:181)
        at org.ethereum.datasource.leveldb.LevelDbDataSource.get(LevelDbDataSource.java:46)
        at org.ethereum.datasource.BatchSourceWriter.get(BatchSourceWriter.java:53)
        at org.ethereum.datasource.WriteCache.get(WriteCache.java:205)
        at org.ethereum.datasource.XorDataSource.get(XorDataSource.java:47)
        at org.ethereum.datasource.XorDataSource.get(XorDataSource.java:30)
        at org.ethereum.datasource.WriteCache.get(WriteCache.java:205)
        at org.ethereum.datasource.WriteCache.get(WriteCache.java:205)
        at org.ethereum.datasource.AsyncWriteCache.get(AsyncWriteCache.java:91)
        at org.ethereum.datasource.SourceCodec.get(SourceCodec.java:53)
        at org.ethereum.datasource.ReadCache.get(ReadCache.java:110)
        at org.ethereum.datasource.SourceChainBox.get(SourceChainBox.java:58)
        at org.ethereum.db.IndexedBlockStore.isBlockExist(IndexedBlockStore.java:196)
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:439)
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:267)
        at org.ethereum.sync.SyncManager.access$600(SyncManager.java:56)
        at org.ethereum.sync.SyncManager$5.run(SyncManager.java:177)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /ethereum-harmony/database/blockchain/551812.ldb: Too many open files
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:316)
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:300)
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:293)
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:85)
        ... 19 common frames omitted
```

**Comment by MysticRyuujin** [comment]
```
chase@HARMONY01:~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31719
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31719
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by zilm13** [comment]
@MysticRyuujin could you increase open files limit and confirm that bug is gone? It could be messed with number of open connections according to similar bugs history.

**Comment by mkalinin** [comment]
@MysticRyuujin please, confirm if this is still reproduced in [1.7.0](https://github.com/ethereum/ethereumj/releases/tag/1.7.0)

**Comment by MysticRyuujin** [comment]
Using the latest git pull from yesterday, I was able to successfully sync the mainnet! 🎉
