### ISSUE TITLE
Snappy compression bug

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#977]
Stacktrace thrown:
Related: [Stackoverflow issue](https://stackoverflow.com/questions/26435179/snappy-java-uncompress-fails-for-valid-data)

<details>
 <summary>Log</summary>
<code>
  io.netty.handler.codec.DecoderException: java.io.IOException: FAILED_TO_UNCOMPRESS(5)
          at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
          at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
          at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
          at org.ethereum.net.rlpx.NettyByteToMessageCodec.channelRead(NettyByteToMessageCodec.java:73)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
          at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:203)
          at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)
          at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:521)
          at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:351)
          at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:322)
          at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:299)
          at org.ethereum.net.rlpx.HandshakeHandler.decode(HandshakeHandler.java:107)
          at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
          at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
          at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
          at org.ethereum.net.server.WireTrafficStats$TrafficStatHandler.channelRead(WireTrafficStats.java:103)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
          at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
          at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
          at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
          at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
          at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
          at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
          at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
          at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
          at java.lang.Thread.run(Thread.java:745)
  Caused by: java.io.IOException: FAILED_TO_UNCOMPRESS(5)
          at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98)
          at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
          at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:474)
          at org.ethereum.net.rlpx.SnappyCodec.decode(SnappyCodec.java:90)
          at org.ethereum.net.rlpx.SnappyCodec.decode(SnappyCodec.java:39)
          at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
          at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
          ... 33 common frames omitted
</code>
</details>

@mkalinin if you could add anything, you are welcome. For example, how to reproduce this bug.

**Comment by zilm13** [comment]
Should be fixed with #980
