### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by holiman** [ethereum/ethereumj#990]
When running tests on hive, sometimes this appears: 

```
06:03:32.767 INFO [o.a.c.h.Http11NioProtocol]  Initializing ProtocolHandler ["http-nio-8545"]
06:03:32.861 ERROR [o.s.s.s.TaskUtils$LoggingErrorHandler]  Unexpected error occurred in scheduled task.
java.lang.ArithmeticException: / by zero
	at com.ethercamp.harmony.service.BlockchainInfoService.calculateHashRate(BlockchainInfoService.java:339)
	at com.ethercamp.harmony.service.BlockchainInfoService.doUpdateBlockchainStatus(BlockchainInfoService.java:288)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

Example logfile: http://35.176.207.236/#displayLog=artefacts/20180112_135508-ethereumj%3Adevelop/client-41b3b648.log , testfile: https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/stSpecialTest/block504980_d0g0v0.json

**Comment by zilm13** [comment]
@holiman yeah, I saw this, it's an ethereum harmony bug, not ethereumj
should be fixed, yeah

**Comment by zilm13** [comment]
should be fixed now in develop
in master only after next release
